(function(g){var window=this;var nxa=function(a){for(var b='<div class="_myp">',c=a.uC+1,d=1;d<c;d++){var e;a.Fl[d]?(e=g.$e(a.Fl[d],{ratio:.3958333333333333}),e='<span class="_mzp">'+(0,g.I)('<img class="_mop"'+(e.lC?'src="'+g.K(g.pf(g.Po()))+'" style="border:0;background-position: 0px -'+g.K(g.qf(e.il*e.ratio))+"px;-webkit-background-size:100% "+g.K(g.qf(e.height*e.ratio))+"px;-moz-background-size:100% "+g.K(g.qf(e.height*e.ratio))+"px;background-image:url("+g.K(g.pf(e.url))+');"':'src="'+g.K(g.pf(e.url))+'" height="'+g.K(e.height*
e.ratio)+'"')+">")+"</span>"):e='<span class="_mzp _maq"></span>';b=b+e}return(0,g.I)(b+"</div>")};
var oxa=function(a){var b=g.I,c='<div class="_mqf _mpp"><a href="#'+g.K(a.fl.url)+'" onclick="return clk(this);">',d;d=a.fl;var e=g.I,f='<div class="_muf _mtp"><div class="_mvf">'+(d.Fl&&0<d.Fl.length?g.J(g.Iq(d.Fl[0])):"")+'</div><div class="_mup"><div class="_mvp"><span class="_mwp">'+g.H(d.videoCount)+'</span><span class="_mxp">',k;k="";var l=g.Vo(new g.To("{VIDEO_COUNT,plural,=0{ videos}=1{ video}other{ videos}}"),{VIDEO_COUNT:d.videoCount});k=(0,g.I)(k+l);d=e(f+g.H(k)+"</span></div>"+(g.zf?nxa(g.$e(d,
{uC:2})):nxa(g.$e(d,{uC:1})))+"</div></div>");return b(c+d+'<div class="_mqp"><div class="_mrp"><h4 class="_msp">'+g.H(a.fl.Ib)+"</h4></div></div></a></div>")};var O8=function(a){var b=a.xc,c=a.name,d=!!a.enabled;return(0,g.I)('<input type="hidden" name="'+g.K(b)+'" value="'+g.K(d?"true":"false")+'"/><a href="#" '+g.L((0,g.ui)(a.lf,b))+' class="_mee"><div class="_mfe _mge"'+g.L((0,g.O)(""))+">"+g.H(c)+'</div><div class="_mle"'+g.L((0,g.O)(""))+">"+(d?g.J(g.AA()):g.J(g.BA()))+"</div></a>")};
var pxa=function(){return(0,g.I)("Send me digest emails with the latest videos from my subscriptions:")};var P8=function(a){var b;a?b={Fl:(0,g.qr)(a.thumbs_info),Ib:(0,g.I)(a.title),url:a.url,username:a.username,videoCount:a.video_count,ak:(0,g.I)(a.description),sb:a.encrypted_id,$y:a.is_public,type:a.type,A0:a.is_watch_later}:b=a;return b};var qxa=function(){return(0,g.I)("Delete Video")};
var rxa=function(){if("undefined"!=typeof Q8)return Q8;var a=g.pc("div"),b=g.Jo({style:{"-webkit-transition":"all 1s linear"}},"");a.innerHTML=g.ib(b);return Q8=g.n(a.firstChild.style.webkitTransition)};var sxa=function(a){return(0,g.I)((a.ci?"":'<a href="#'+g.K(a.fl.url)+'" onclick="return clk(this)">')+oxa(a)+(a.ci?"":"</a>"))};var R8=function(a,b,c){g.Uv.call(this,a,b,c);this.oh=!1;this.b=[];this.ig=g.iA();this.Kz=g.Vp();this.rg=!1;this.Yi=[g.jA()];this.$f=null};
var txa=function(a){a.Wi=(0,g.M)(a.b,function(a,c){return(0,g.I)(this.bD(a,c))},a)};var uxa=function(a,b){g.rp(b,(0,g.x)(function(a){this.la(a.content);this.nd()},a))};
var vxa=function(a){var b=a.pC,c=a.xsrf_token;a='<div class="_mme"><a href="/account_notifications" class="_mne" onclick="return clk(this);"><div class="_mhe _mqe"><div class="_mke _mre"></div></div><h2>'+g.J(g.kA())+'</h2></a><div class="_mne"><div class="_mse _mge">'+pxa()+"</div><form class=\"_mge\" method='post' "+g.L(g.P("emailLocaleForm"))+' action=\'/account_notifications?action_save_email_locale=1&ajax=1\'><input type="hidden" name="session_token" value="'+g.K(c)+'"/><div class="_mte"><div class="_mue"><select name="email_locale" '+
g.L(g.vi("onchange",a.gR))+" "+g.L(g.P("emailLocaleSelect"))+'class="_mve _mwe">';for(var c=b.length,d=0;d<c;d++){var e=b[d];a+="<option "+(e.selected?"selected":"")+' value="'+g.K(e.value)+'"'+g.L((0,g.O)(""))+"dir="+g.hq(e.dir)+">"+g.H(e.name)+"</option>"}return(0,g.I)(a+"</select></div></div></form></div></div>")};
var wxa=function(a){var b=a.qC,c=a.xsrf_token;a='<div class="_mme"><a href="/account_notifications" class="_mne" onclick="return clk(this);"><div class="_mhe _mqe"><div class="_mke _mre"></div></div><h2>'+g.J(g.kA())+'</h2></a><div class="_mne"><div class="_mse _mge">'+pxa()+"</div><form class=\"_mge\" method='post' "+g.L(g.P("frequencyForm"))+' action=\'/account_notifications?action_save_frequency=1&ajax=1\'><input type="hidden" name="session_token" value="'+g.K(c)+'"/><div class="_mte"><div class="_mue"><select name="digest_frequency" '+
g.L(g.vi("onchange",a.hR))+" "+g.L(g.P("frequencySelect"))+'class="_mve _mwe">';for(var c=b.length,d=0;d<c;d++){var e=b[d];a+="<option "+(e.selected?"selected":"")+' value="'+g.K(e.value)+'"'+g.L((0,g.O)(""))+">"+g.H(e.name)+"</option>"}return(0,g.I)(a+"</select></div></div></form></div></div>")};
var xxa=function(a){var b=a.ue,c=a.Tm,d=a.mr,e=a.zx,f=a.xsrf_token,k=!!a.av,l=a.wn,p=a.Le,u=a.Cd,C=a.Fe,z='<form class="_mme" method="post"'+g.L(g.P("notificationsForm"))+'action="/account_notifications?action_save=1&ajax=1">'+g.J(g.Mr())+'<div class="_mne"><h2 class="_moe">',F;F=(0,g.I)("Emails about your subscriptions");b=z+F+"</h2>"+(g.Dm?"":"<hr />")+'<input type="hidden" name="digest_frequency" value="'+g.K(b)+'"/><a href="#/account_notifications?action_digest_frequency=1" class="_mee" onclick="return clk(this);"><div class="_mfe _mge">'+
g.FA()+'</div><div class="_mle">'+g.H(c)+'</div><div class="_mhe _mie">'+(g.Dm?'<div class="_mje"></div>':'<div class="_mke"></div>')+"</div></a>";c=p.length;for(z=0;z<c;z++)F=p[z],b+=(g.Dm?"":"<hr />")+O8({xc:F.xc,name:F.name,enabled:F.enabled,lf:a.lf});""!=l?(k=k?(0,g.I)("Comment notifications"):(0,g.I)("Comments on your channel"),k='<div class="_mne"><h2 class="_moe">'+k+"</h2>"+(g.Dm?"":"<hr />"),l=g.I,p='<a href="'+g.K(g.jf(a.wn))+'" class="_mee"><div class="_mfe _mge">',c=(0,g.I)("Change on Google+"),
l=l(p+c+'</div><div class="_mhe _mie">'+(g.Dm?'<div class="_mje"></div>':'<div class="_mke"></div>')+"</div></a>"),k=k+l+"</div>"):k="";f="</div>"+k+'<input type="hidden" name="session_token" value="'+g.K(f)+'"><div class="_mne"><h2 class="_moe">';k=(0,g.I)("Emails about your channel");b=b+(f+k+"</h2>"+(g.Dm?"":"<hr />"));f=u.length;for(k=0;k<f;k++)l=u[k],b+=(0==k||g.Dm?"":"<hr />")+O8({xc:l.xc,name:l.name,enabled:l.enabled,lf:a.lf});u=b;f=(0,g.I)("YouTube Newsletters");b=u+('</div><div class="_mne"><h2 class="_moe">'+
f+"</h2>"+(g.Dm?"":"<hr />"));u=C.length;for(f=0;f<u;f++)k=C[f],b+=(0==f||g.Dm?"":"<hr />")+O8({xc:k.xc,name:k.name,enabled:k.enabled,lf:a.lf});C=b;u='</div><div class="_mne"><h2 class="_moe">'+(0,g.I)("Language for emails")+"</h2>"+(g.Dm?"":"<hr />")+'<a href="#/account_notifications?action_email_locale=1" class="_mee" onclick="return clk(this);"><div class="_mfe _mge">';f=(0,g.I)("Language");a=u+f+'</div><div class="_mle" dir='+g.hq(e)+">"+g.H(d)+'</div><div class="_mhe _mie">'+(g.Dm?'<div class="_mje"></div>':
'<div class="_mke"></div>')+'</div></a></div><input type="hidden" name="block_emails" value="false"/><a href="#" class="_mne" '+g.L((0,g.ui)(a.FN))+'><h2 class="_mpe">';d=(0,g.I)("Turn off all emails");b=C+(a+d+'</h2><div class="_mhe _mie">'+(g.Dm?'<div class="_mje"></div>':'<div class="_mke"></div>')+"</div></a></form>");return(0,g.I)(b)};var S8=function(){return(0,g.I)("Never")};
var yxa=function(a){var b;b=""+('<div class="_mth"><div class="_muh">Are you sure you want to unsubscribe?</div></div>'+g.J(g.gA({href:(0,g.dn)("/channel/"+g.hf(a.itemId)),Ce:(0,g.ch)("Keep subscription")}))+g.J(g.gA({Ce:(0,g.ch)("Unsubscribe"),ia:a.OP}))+'<p class="_mqo">'+g.H(a.vS)+"</p>");if(0!=a.Yh.length){b+='<div class="_mwh"><ul>';a=a.Yh;for(var c=a.length,d=0;d<c;d++){var e=a[d];b+='<li class="_mso"><img src="'+g.K(g.pf(e.Qs))+'" class="_mto"/><span class="_mfe">'+g.H(e.title)+"</span></li>"}b+=
"</ul></div>"}b+=g.J(g.rj({Ab:g.bf("_muo"),sa:(0,g.ch)("Help"),Ee:(0,g.dn)("//support.google.com/youtube?p=mweb_transact_help")}));return(0,g.I)(b)};var zxa=function(a,b){g.wj.call(this,Axa,qxa());this.video=a;this.Tk=b};var Bxa=function(){g.uf("/logout")};
var Cxa=function(a){var b=a.style;rxa()?b.display="none":(b.webkitTransition="",b.height=a.scrollHeight+"px",b.overflow="hidden",(0,window.setTimeout)(function(){b.webkitTransition="height 0.2s ease-out";(0,window.setTimeout)(function(){b.height=0},0)},0))};var Dxa=function(){return(0,g.I)("Playlists")};var Exa=function(){return(0,g.I)("Sign out")};var Fxa=function(){return(0,g.I)("Privacy Settings")};var Gxa=function(){return(0,g.I)("OK")};
var Hxa=function(a){return g.Qe(a,g.Ne)?g.ef(a.getContent()):g.ta(String(a))};var T8=function(){g.Uv.call(this,"account_notifications",{},xxa);this.zf=!0;this.xsrf_token=this.zx=this.mr=this.Tm=this.ue="";this.b=0;this.g=!0;this.av=!1;this.wn="";this.Le=[];this.Cd=[];this.Fe=[];g.Zn(this,!0)};var U8=function(a,b,c){return{xc:a,name:b,enabled:!!c[a]}};
var V8=function(a,b,c){var d=a.Y("notificationsForm"),e=(0,g.x)(function(a){this.b--;this.b||g.Zn(this,!1);g.Q(this);g.Qi(g.Ui(a))},a);d.elements[b].value=c;g.wA(d,e,g.sp);g.Zn(a,!0);a.b++};var W8=function(){g.Uv.call(this,"account_notifications",{action_digest_frequency:1},wxa);this.zf=!0;this.g=this.xsrf_token="";this.qC=null;this.b=0};var Ixa=function(a){a.qC=(0,g.M)([["d",g.GA()],["w",g.HA()],["n",S8()]],function(a){return{name:a[1],value:a[0],selected:a[0]==this.g}},a)};
var X8=function(){g.Uv.call(this,"account_notifications",{action_email_locale:1},vxa);this.zf=!0;this.g=this.xsrf_token="";this.pC=null;this.b=0};var Jxa=function(a,b){a.pC=(0,g.M)(b,function(a){return{name:a[1],value:a[0],selected:a[0]==this.g,dir:g.Lo(a[1])?"rtl":"ltr"}},a)};
var Kxa=function(a){var b='<div class="_mme">'+g.J(g.Mr())+'<form method="post"'+g.L(g.P("privacyForm"))+'action="/account_privacy?action_save=1&ajax=1"><input type="hidden" name="session_token" value="'+g.K(a.Pb)+'"><input type="hidden" name="updated_element" value="">';a=a.VB;for(var c=a.length,d=0;d<c;d++)b+=g.J(g.rA({su:a[d]}));return(0,g.I)(b+"</form></div>")};var Y8=function(){g.Uv.call(this,"account_privacy",{},Kxa);this.g=null;this.b=0;this.VB=[];this.Pb=""};var Lxa=function(){return(0,g.I)("Delete Google+ Profile")};
var Mxa=function(){return(0,g.I)("On YouTube")};var Z8=function(a){var b="";a='<a href="'+g.K(g.jf(a.An))+'" target="_blank">Learn more</a>';return(0,g.I)(b+a)};var Nxa=function(a){var b="";a="The photo you used with "+(g.H(a.Td)+", if any, will be restored.");return(0,g.I)(b+a)};
var Oxa=function(a){var b=g.I,c='<div class="_mme">'+g.J(g.Mr())+'<div class="_mne"><h2>'+g.H(a.uk)+"</h2><hr /><h4>"+Mxa()+'</h4><ul class="_mxe"><li>',d;d="";var e="The name on the channel will go back to <b>"+(g.H(g.bf(""+a.Td))+"</b>.");d=(0,g.I)(d+e);c=c+d+"</li><li>"+Nxa({Td:g.bf(""+a.Td)})+"</li></ul><hr /><h4>";d=(0,g.I)("On Google+");c=c+d+'</h4><ul class="_mxe"><li>';d="";e="<b>Your profile will still exist</b>, with your name ("+(g.H(g.bf(""+a.jc))+") on it.");d=(0,g.I)(d+e);c=c+d+"</li><li>";
d=(0,g.I)("Your Google+ profile will be disconnected from your YouTube channel.");c=c+d+"</li><li>";d=(0,g.I)("After you disconnect your channel and profile, you can edit your profile, or even delete it.");return b(c+d+'</li></ul><form class="_mge" method=\'post\' action=\'/account_revert?ver=1&action_revert_profile=1\'><input type="hidden" name="session_token" value="'+g.K(a.xsrf_token)+'"/><button class="_mpc _mye _mqc" type="submit" name="submit" value="1">'+g.J(Gxa())+"</button></form></div></div>")};
var Pxa=function(a){var b=g.I,c='<div class="_mme">'+g.J(g.Mr())+'<div class="_mne">',d;d=g.bf(""+a.Td);var e=(0,g.dn)(""+g.jf(a.pB));a="";d="Your channel name is now "+(g.H(d)+(", and is no longer connected with "+('<a href="'+g.K(g.jf(e))+'" onclick="return clk(this);">your Google+ profile</a>.')));d=(0,g.I)(a+d);return b(c+d+"</div></div>")};
var Qxa=function(a){var b=g.I,c='<div class="_mme">'+g.J(g.Mr())+'<div class="_mne"><h2>'+g.H(a.uk)+"</h2><hr /><h4>"+Mxa()+'</h4><ul class="_mxe"><li>',d;d="";var e="The name on the channel will be <b>"+(g.H(g.bf(""+a.Td))+"</b>.");d=(0,g.I)(d+e);return b(c+d+"</li><li>"+Nxa({Td:g.bf(""+a.Td)})+'</li></ul><form class="_mge" method=\'post\' action=\'/account_revert?ver=3R&action_revert_profile=1\'><input type="hidden" name="session_token" value="'+g.K(a.xsrf_token)+'"/><button class="_mpc _mye _mqc" type="submit" name="submit" value="1">'+
g.J(Gxa())+"</button></form></div></div>")};
var Rxa=function(a){var b=g.I,c="",d="Your channel name is now "+(g.H(g.bf(""+a.Td))+", and is no longer connected with your Google+ profile."),c='<div class="_mme"><div class="_mne"><h2>'+(0,g.I)(c+d)+'</h2><br /><form class="_mge" method=\'get\' action=\'/select_site\'><button class="_mpc _mye _mqc" type="submit" name="submit" value="1">'+g.J(g.Zp())+'</button></form></div><div class="_mne"><h2>',d=(0,g.I)("Your Google+ Profile"),c=c+d+'</h2><div class="_mse _mge">',d="";a="Your Google+ profile still exists, with your name ("+
(g.H(g.bf(""+a.jc))+") on it.  If you wish, you can delete your profile now.");a=(0,g.I)(d+a);return b(c+a+'</div><form class="_mge" method=\'get\' action=\'/account_revert\'><input type="hidden" name="ver" value="3R"/><input type="hidden" name="action_explain" value="1"/><button  class="_mpc _mye" type="submit" name="submit" value="1">'+Lxa()+"</button></form></div></div>")};
var Sxa=function(a){var b=g.I,c='<div class="_mme"><div class="_mne"><h4>'+(0,g.I)("If you choose to proceed, Google will delete your Google profile and the features and the data that depend on it.")+"</h4><hr /><h4>",d;d=(0,g.I)("Google+ and its data including:");var c=c+d+'</h4><ul class="_mxe"><li>',e=(0,g.dn)(""+g.jf(a.HH));d="";e="Your circles will be deleted, but people in your circles will remain in your "+('<a href="'+g.K(g.jf(e))+'">Contacts</a>.');d=(0,g.I)(d+e);c=c+d+"</li><li>";d=(0,g.I)("Your +1's will be deleted.");
c=c+d+"</li><li>";d=(0,g.I)("Your posts and comments will be deleted and won't be available to the people or communities you shared them with.");c=c+d+"</li><li>";d=(0,g.I)("Any profile information that you did not make public will be deleted.");c=c+d+"</li><li>";d=(0,g.I)("Many Google+ social and sharing features will be disabled for you on other Google sites.");c=c+d+"</li><li>";d=(0,g.I)("Content from other services, such as videos, will no longer be visible to people in those circles.");c=c+d+
"</li><li>";d=(0,g.I)('No photos will be deleted: you can still access them in Picasa. To delete them, go to <a href="https://picasaweb.google.com">Picasa Web Albums</a>.');c=c+d+"</li><li>";e=(0,g.dn)(""+g.jf(a.WG));d="";e="Your connections to third-party services will not be affected. To manage them go to "+('<a href="'+g.K(g.jf(e))+'">Connected accounts</a> settings.');d=(0,g.I)(d+e);c=c+d+"</li><li>";d=(0,g.I)("Your chat buddies in Google Talk and Gmail will not be deleted.");c=c+d+"</li><li>";
d=(0,g.I)('Your Google+ Local reviews will not be deleted: They will be marked as private and accessible in the "My Places" section of Google Maps. You will be able to delete them there.');c=c+d+" "+Z8({An:(0,g.dn)(""+g.jf(a.IL))})+"</li><li>";d=(0,g.I)("No communities you created will be deleted, unless you're the only member.");c=c+d+"</li></ul><hr /><h4>";d=(0,g.I)("Google+ Pages");c=c+d+'</h4><ul class="_mxe"><li>';d=(0,g.I)("Pages you own");c=c+d+"<br>";d=(0,g.I)("No Google+ pages that you own will be deleted. If you don't want to own a page any more, you can delete it. Deleting a page is permanent. You can also transfer ownership of a page, using the page's settings.");
c=c+d+" "+Z8({An:(0,g.dn)(""+g.jf(a.JL))})+"</li><li>";d=(0,g.I)("Pages you manage");c=c+d+"<br>";d=(0,g.I)("You can continue to manage any pages you currently manage. Your name and email address will be visible to the owner and the other managers of any page you manage. You can also remove yourself as a manager of a page, using the page's settings. If you do, you'll no longer be able to act as that page or take any kind of administrative actions. However, all of your past posts, comments, and other actions will remain intact.");
c=c+d+" "+Z8({An:(0,g.dn)(""+g.jf(a.KL))})+"</li></ul><hr /><h4>";d=(0,g.I)("Google Buzz and all Buzz posts will be deleted.");c=c+d+"</h4><hr /><h4>";d=(0,g.I)("Your public Google profile will be removed.");c=c+d+'</h4><ul class="_mxe"><li>';d=(0,g.I)("Deleting your public profile will not affect the status of your Google Account.");c=c+d+"</li></ul><hr /><h4>";d=(0,g.I)("Other Google products which require a profile will be impacted.");c=c+d+" "+Z8({An:(0,g.dn)("//www.google.com/support/+/?p=downgrade")})+
'</h4><hr /><form class="_mge" method=\'post\' action=\'/account_revert?ver=3R&action_delete_profile=1\'><input type="hidden" name="session_token" value="'+g.K(a.xsrf_token)+'"/><label class="_mze"><input type="checkbox" name="unfollow_me" '+(a.BC?"checked":"")+" "+g.L(g.P("unfollowCheckbox"))+">";d=(0,g.I)("Also unfollow me from anyone I am following in Buzz, Google Reader, and other Google products.");c=c+d+'</input></label><label class="_mze"><input type="checkbox" name="i_understand" '+(a.Hu?
"":"checked")+" "+g.L(g.P("acceptCheckbox"))+" "+g.L(g.vi("onchange",a.CP))+">";d=(0,g.I)("<b>Required</b>: I understand that deleting this service can't be undone and the data I delete can't be restored.");return b(c+d+'</input></label><button  class="_mpc _mqc _mye"  type="submit" name="submit" value="1" '+g.L(g.P("submitButton"))+" "+(a.Hu?"disabled":"")+">"+Lxa()+"</button></form></div></div>")};var $8=function(){g.Uv.call(this,"account_revert",{ver:"1"},Oxa)};
var a9=function(){g.Uv.call(this,"account_revert",{ver:"1",action_done:1},Pxa)};var b9=function(){g.Uv.call(this,"account_revert",{ver:"3R"},Qxa)};var c9=function(){g.Uv.call(this,"account_revert",{ver:"3R",action_done:1},Rxa)};var d9=function(){g.Uv.call(this,"account_revert",{ver:"3R",action_explain:1},Sxa)};
var Txa=function(a){var b=g.I;if(g.Dm){for(var c='<div class="_mbi"><div class="_mvh">'+Uxa()+'</div></div><div class="_mwh _mci">',d=a.$u,e=d.length,f=0;f<e;f++)var k=d[f],c=c+(k.Pm?'<a href="'+g.K(g.jf(k.Pm))+'" onclick="return clk(this);"><h2>'+Vxa()+'</h2><div class="_mhe _mie"><div class="_mje"></div></div></a>':(k.uj?'<a href="#'+g.K(k.uj)+'" onclick="return clk(this);" '+g.L((0,g.O)(""))+(g.If?'aria-selected="'+g.K(k.Kk)+'" role="option"':'aria-pressed="'+g.K(k.Kk)+'" role="button"')+(k.Zy?
' class="_mdi"':' class="_mei"')+">":"")+'<span class="_mai _mwe" >'+g.H(k.Ox)+'</span><div class="_mfi"><div class="_mzh">'+g.J(g.Kp({size:32,Tc:k.Xa}))+'</div><h2 class="_mwe">'+g.H(k.pw)+"</h2>"+(k.Kk?'<div class="_mhe _mie"><div class="_msd"></div></div>':'<div class="_mhe _mie"><div class="_mje"></div></div>')+"</div>"+(k.uj?"</a>":""));c+=(a.Dn||a.pj?"":'<a href="'+g.K(g.jf(a.Aw))+'" onclick="return clk(this);"><h2>'+Wxa()+'</h2><div class="_mhe _mie"><div class="_mje"></div></div></a>')+(a.Dn?
"":a.Fa?g.J(g.ah(a)):a.pj?'<a href="'+g.K(g.jf(a.pj))+'"><h2>'+Xxa()+'</h2><div class="_mhe _mie"><div class="_mje"></div></div></a>':'<a href="'+g.K(g.jf(a.hC))+'"'+g.L((0,g.ui)(Bxa))+g.L((0,g.O)(""))+"><h2>"+g.J(Exa())+'</h2><div class="_mhe _mie"><div class="_mje"></div></div></a>')+"</div>"}else{c='<div class="_mth"><div class="_muh"><div class="_mvh">'+Uxa()+'</div></div></div><div class="_mwh">';d=a.$u;e=d.length;for(f=0;f<e;f++)k=d[f],c+=(k.Pm?'<a href="'+g.K(g.jf(k.Pm))+'" onclick="return clk(this);"><h2>'+
Vxa()+"</h2></a>":(k.uj?'<a href="#'+g.K(k.uj)+'" onclick="return clk(this);" aria-pressed="'+g.K(k.Kk)+'" '+g.L((0,g.O)(""))+">":"")+'<div class="_mqf '+(k.Kk?"_mxh":"")+(k.Zy?"":" _myh")+'"><div class="_mzh">'+g.J(g.Kp({size:48,Tc:(0,g.dn)(""+g.jf(k.Xa))}))+'</div><h2 class="_mwe">'+g.H(k.pw)+'</h2><span class="_mai _mwe" >'+g.H(k.Ox)+"</span></div>"+(k.uj?"</a>":""))+"<hr />";c+=(a.Dn||a.pj?"":'<a href="'+g.K(g.jf(a.Aw))+'" onclick="return clk(this);"><h2>'+Wxa()+"</h2></a>")+"</div>"+(a.Dn?"":
a.Fa?g.J(g.ah(a)):a.pj?'<a href="'+g.K(g.jf(a.pj))+'" class="_mne"><h2>'+Xxa()+'</h2><div class="_mhe _mie"><div class="_mke"></div></div></a>':'<a href="'+g.K(g.jf(a.hC))+'"'+g.L((0,g.ui)(Bxa))+g.L((0,g.O)(""))+'class="_mne"><h2>'+g.J(Exa())+'</h2><div class="_mhe _mie"><div class="_mke"></div></div></a>')}a=(0,g.I)(c);return b(a)};var Uxa=function(){return(0,g.I)("Use YouTube as...")};var Wxa=function(){return(0,g.I)("Add Account")};var Vxa=function(){return(0,g.I)("Create a new channel")};
var Xxa=function(){return(0,g.I)("Manage Accounts")};var Yxa=function(a,b,c,d,e,f,k){this.pw=a;this.Ox=b;this.Xa=c;this.uj=d;this.Kk=e;this.Zy=f;this.Pm=k};var e9=function(a){g.Uv.call(this,"channel_switcher",a,Txa);this.ho=Txa;g.Wi||g.uf(g.Il());this.$u=[new Yxa(g.Wi,g.Lm,g.ym,null,!0,!0,null)];this.hC=g.Wi?"/logout":""};
var Zxa=function(a){return(0,g.I)('<div class="_mqf"><div class="_mmk">'+(a.Be?'<div class="_mnk">'+(a.aj?'<a href="#" '+g.L((0,g.ui)(a.aj,a.index))+g.L((0,g.O)(""))+'><div class="_mok"></div></a>':"")+"</div>":"")+'<div class="_mpk">'+g.H(a.hx)+"</div>"+(a.Be&&a.zk?a.Is?'<div class="_mqk"><div class="_mgb"><div class="_mrk"></div></div></div>':a.to?'<div class="_mqk"><div '+g.L((0,g.ui)(a.to,a.index))+" "+g.L((0,g.O)(""))+'><div class="_msk"></div></div></div>':"":"")+"</div></div>")};
var $xa=function(a){var b=g.I;a=a.bp?g.J(g.ah({text:(0,g.ch)(""+g.J(g.Xp()))})):a.ul?(0,g.I)('<form action="'+g.K(g.jf(a.EB))+'" method="post"'+g.L(g.P("form"))+g.L(g.vi("onsubmit",a.hP,a.Ay))+">"+aya(a)+'<div class="_mri">'+g.J(g.xi("editor",a.xx))+"</div></form>"):a.xu?(0,g.I)('<form action="'+g.K(g.jf(a.IG))+'" method="post"'+g.L(g.P("form"))+g.L(g.vi("onsubmit",a.eP))+">"+aya(a)+'<div class="_mri">'+g.J(g.xi("builder",a.eI))+"</div></form>"):g.J(g.xi("title",bya))+'<div class="_mri">'+g.J(g.xi("list",
g.hA))+"</div>";return b(a)};
var bya=function(a){var b;b=g.bf("_msi");var c;c=g.bf("_mti");a=""+('<div class="_mwh '+(a.ex?"_mti":"")+'" '+g.L(g.P("editableListCard"))+'><div class="_mui"'+(a.ex?g.L((0,g.ui)(a.Bh,"editableListCard",b,c)):"")+">"+g.J(g.xi("titleText",a.gi))+"</div>"+(a.zk?'<hr /><div class="_mtk">'+(a.Be&&a.Vz?'<a href="#" '+g.L((0,g.ui)(a.Vz))+" "+g.L((0,g.O)(""))+">"+g.H(a.xw)+"</a>":"")+'<a href="#" '+g.L((0,g.ui)(a.jt))+" "+g.L((0,g.O)(""))+">"+g.H(a.yx)+"</a></div>":"")+"</div>");return(0,g.I)(a)};
var aya=function(a){return(0,g.I)(g.J(g.lA({kz:(0,g.ch)(""+g.J(g.pj({sa:(0,g.ch)(""+g.J(g.Vg())),ia:a.bN,ob:"cancel"}))),Ib:(0,g.ch)(""+(a.gi?g.J(g.xi("titleText",a.gi)):"")),zB:(0,g.ch)(""+g.J(g.qj({sa:(0,g.ch)(""+g.J(g.So())),ob:"save"})))})))};var cya=function(){this.b=[];this.g=[]};var f9=function(a,b){for(;a.length&&250<b-a[1]||10<a.length;)a.splice(0,2)};var dya=function(a,b,c,d){return a<<21|b<<14|c<<7|d};
var g9=function(a){return function(b){b.touches=[];b.targetTouches=[];b.changedTouches=[];b.type!=eya&&(b.touches[0]=b,b.targetTouches[0]=b);b.changedTouches[0]=b;a(b)}};var fya=function(a){var b;if(b=g.ua(window.navigator.userAgent,"Android")&&g.ua(window.navigator.userAgent,"Chrome/"))b=gya.exec(window.navigator.userAgent),b=18==+(b?b[1]:"").split(".")[0];return b?new g.Pn(a.clientX,a.pageY-window.scrollY):new g.Pn(a.clientX,a.clientY)};var h9=function(a){return(i9?[a]:a.changedTouches)||[]};
var j9=function(a){return i9?a.pointerId:a.identifier};var hya=function(a){if(!(2500<(0,g.G)()-iya)){var b=fya(a);if(!(1>b.x&&1>b.y)){for(var c=0;c<k9.length;c+=2)if(25>Math.abs(b.x-k9[c])&&25>Math.abs(b.y-k9[c+1])){k9.splice(c,c+2);return}a.stopPropagation();a.preventDefault();(a=l9)&&a()}}};var jya=function(a){var b=fya((a.touches||[a])[0]);k9.push(b.x,b.y);window.setTimeout(function(){for(var a=b.x,d=b.y,e=0;e<k9.length;e+=2)if(k9[e]==a&&k9[e+1]==d){k9.splice(e,e+2);break}l9=void 0},2500)};
var m9=function(a,b,c){this.N=a;this.R=b;this.o=c;this.g=[];this.B=[];this.G=[];this.H=[];this.C=[];this.D=[]};var n9=function(a,b){for(var c,d=h9(b),e=d.length,f=0;f<a.b;f++){a.B[f]=void 0;for(var k=0;k<e;k++)if(a.g[f]==j9(d[k])){a.B[f]=d[k];c=!0;break}}return c};var kya=function(a,b){var c=b||0,d=a.B[c];return d?d.clientX:a.N[a.g[c||0]]};var lya=function(a,b){var c=b||0,d=a.B[c];return d?d.clientY:a.R[a.g[c||0]]};var o9=function(a,b,c){m9.call(this,b,c,1);this.L=a;this.J=new cya};
var p9=function(a,b,c){m9.call(this,b,c,2);this.J=a};var q9=function(a){this.A=a;this.B=this.A.Y();this.g={};this.o={};this.b=[]};var mya=function(a,b){a.A.yo(null);for(var c=a.b.length,d=0;d<c;d++){var e=a.b[d];if(e){var f=e;if(!f.F&&0<f.b){for(var e=void 0,k=0;k<f.b;k++)if(f.g[k]==b){e=k;break}g.n(e)&&(f.A&&f.M(null),f.g.splice(e,1),f.b--,f.A=!1)}}}delete a.g[b];delete a.o[b]};
var nya=function(a){this.ve=a;this.B=g.Nh(window.document,r9,(0,g.x)(this.eT,this));this.A=g.Nh(window.document,s9,(0,g.x)(this.dT,this));this.o=g.Nh(window.document,t9,(0,g.x)(this.cT,this))};var u9=function(a){void 0!=a.b&&(window.clearInterval(a.b),a.b=void 0)};var v9=function(a,b,c){this.ve=a;this.cI=b;this.pJ=c||b};var w9=function(a){this.ve=a;this.b=this.$j=null;this.o=[];this.D=new nya(this)};var oya=function(a,b){a.B=b};
var x9=function(a){q9.call(this,a);var b=this.b[0];b||(b=new pya[0](a,this.g,this.o),this.b[0]=b);this.enable()};var qya=function(a,b,c){var d=a.$j,e=a.b;g.oq(e,e.offsetLeft,b-e.b);a:{for(var e=g.uc(a.ve),f=0,k=e.length;f<k;f++)if(b<e[f].Nw){e=e[f];break a}e=null}d!=e&&a.ve.insertBefore(d,e);a.g=g.El.Nc.fd();a.C=b;g.Th(window.document,s9,a,c)};var y9=function(a){a.b&&g.sc(a.b);a.$j&&(a.$j.style.visibility="visible")};
var z9=function(a,b){R8.call(this,a,b,$xa);this.o="";this.ul=this.Be=this.Is=this.zk=!1;this.yx=g.Yp();this.xw="";this.ex=!1;this.g=null};var rya=function(a){if(a.Is&&a.Be){a.g&&(a.g.dispose(),a.g=null);var b=g.ic("_meb",a.Y("list"));b&&(a.g=new w9(b),a.g.A="_mfb",oya(a.g,function(a){return g.ic("_mgb",a)}),a.g.init(),a.B||(a.B=g.Nh(window.document,t9,(0,g.x)(a.hT,a))))}};var sya=function(a,b){a.Be=b;a.yx=b?g.Zp():g.Yp();g.Q(a,"title");!b&&a.ul?A9(a):a.nd()};
var B9=function(a,b){var c=g.gc("_mhb",a.Y("list"))[b];c&&(c.firstChild.style.visibility="hidden",Cxa(c.firstChild))};var C9=function(a,b,c){a.ul=!0;a.xu=!1;a.Mb=b;a.Ay=c;a.nd();a.zi=!0;g.Q(a,"header");a.ne(1)};var tya=function(a){a.xu=!0;a.ul=!1;a.nd();a.zi=!0;g.Q(a,"header");a.ne(1)};var A9=function(a){a.ul=!1;a.xu=!1;a.Mb=a.Ay=null;a.nd();a.zi=!1;g.Q(a,"header")};var D9=function(a,b){z9.call(this,a,b);this.Yi=[g.Nq()];this.ig=g.Oq()};var E9=function(a){D9.call(this,"my_favorites",a)};
var F9=function(a){D9.call(this,"my_history",a)};
var uya=function(a){var b=g.I,c;a.Mb?(c=(0,g.I)(oxa({fl:a.Mb})),c='<div class="_meb">'+g.H(c)+'</div><input type="hidden" name="p" value="'+g.K(a.Mb.sb)+'">'):c="";c='<div class="_mwn">'+c+'<div class="_mxn"><div class="_myn">';var d;d=(0,g.I)("Title");c=c+g.H(d)+'</div><input type="text" name="playlist_name"'+(a.Mb?'value="'+g.K(a.Mb.Ib)+'"':"")+'class="_mzi"></div><div class="_mxn"><div class="_myn">';d=(0,g.I)("Description");return b(c+g.H(d)+'</div><textarea name="playlist_description" rows="5" class="_mzi">'+(a.Mb?
Hxa(a.Mb.ak):"")+'</textarea></div><div class="_mxn"><div class="_myn">'+g.J(Fxa())+'</div><div class="_mue"><select class="_mve _mzn" name="playlist_privacy"><option value="public"'+(a.Mb&&a.Mb.$y?'selected="selected"':"")+">"+g.J(g.Ro())+'</option><option value="private"'+(a.Mb&&!a.Mb.$y?'selected="selected"':"")+">"+g.J(g.Qo())+"</option></select></div></div></div>")};
var G9=function(a){z9.call(this,"my_playlists",a);(0,g.I)("Sorry, no playlists are available");(0,g.I)("Show more playlists");this.EB="/manage_playlist?action_save=1";this.IG="/manage_playlist?action_create_playlist=1";this.xw=(0,g.I)("Create a playlist");g.dA(this,Dxa())};var vya=function(a){return"WL"==a||"FL"==a};
var Axa=function(a){var b=g.I,c=g.J(g.Jq(a))+'<div class="_mao">',d;d=(0,g.I)("Are you sure you want to delete this video?");return b(c+g.H(d)+"</div>"+g.J(g.qj({ia:a.Tk,ob:"confirm_delete",sa:(0,g.ch)(""+g.J(qxa()))})))};var H9=function(a){D9.call(this,"my_videos",a);this.EB="/manage_videos?action_save=1"};
var wya=function(a){var b;b=""+('<div class="_mth"><div class="_muh">Select a purchase option</div></div>'+(a.Hz?'<div class="_mho">'+g.H(a.Hz)+' <a href="'+g.K(g.jf(a.Iz))+'" target="_blank" class="ypcMusicBannerHelpUrl">'+g.H(a.fM)+"</a></div>":"")+'<div class="_mne"><ul>');for(var c=a.no.sM,d=c.length,e=0;e<d;e++){var f=c[e],k=b,l;l=a.qh;b=f.fz;var p=f.Nz[0],u="",C=b.Ks,u=u+((C?'<a href="'+g.K(g.jf(b.Dx))+'" target="_blank">':"")+g.J(g.Kp({Tc:b.gS,size:55}))+(C?"</a>":"")+'<div class="_mlo"><div>'),
u=C?u+('<a href="'+g.K(g.jf(b.Dx))+'" target="_blank">'+g.H(b.title)+"</a>"):l?u+"YouTube Music Key":u+g.H(b.title),u=u+"</div>",z=b.subtitle,u=u+(z&&!C?'<div class="_mmo">'+g.H(z)+"</div>":"");C&&(C=b.rQ,C=g.Vo(new g.To("{CHANNEL_COUNT_1,plural,=0{Includes 0 channels}=1{Includes 1 channel}other{Includes {CHANNEL_COUNT_2} channels}}"),{CHANNEL_COUNT_1:C,CHANNEL_COUNT_2:g.H(C)}),u+='<div class="_mmo">'+C+"</div>");b=b.BL;u+='<div class="_mmo">'+(l?"":xya({hf:p,qh:l,Vy:b}));b&&!l&&(u+='<span class="_mno">',
u=p.Uy?u+"No advertising":u+"May include ads",u+="</span>");u+="</div></div>";l=(0,g.I)(u);b=k+('<li><div class="_mio">'+l+"</div><ul>");k=f.Nz;l=k.length;for(p=0;p<l;p++){u=k[p];if(a.qh)C="",C+='<p class="_moo"><span class="_mpo">Beta Access</span><span>'+xya({hf:u,qh:!0,Vy:!0})+"</span></p>",C=(0,g.I)(C);else{var C=f.fz,z=u,F="";if(z.zL||z.AL)F=z.wL?F+"HD":F+"SD";else if(z.az){var R="";C.yL?R=z.Uy?R+"Ads-free":R+"Ad-supported":z.Wy?R+="Daily":z.Xy?R+="Monthly":z.bz&&(R+="Annual");C=(0,g.I)(R);F=
F+C}C=(0,g.I)(F)}b=b+('<hr /><li><span class="_mfe _mge">'+C+'</span><span class="_mle">');C="";u.cy?C=C+"Start free trial":(F=u,z="",F.az?F.Wy?(F=g.H(F.Um)+"/day",z+=F):F.Xy?(F=g.H(F.Um)+"/month",z+=F):F.bz&&(F=g.H(F.Um)+"/year",z+=F):z+=g.H(F.Um),z=(0,g.I)(z),C+=z);b+=g.J(g.rj({ia:a.DO,Wc:u,ob:"ypc_mobile_offer",style:g.bf("_mjo"),sa:(0,g.ch)(C)}));b+="</span></li>"}b+="</ul></li>"}b+="</ul></div>";a.qh&&a.eM&&(c=g.H(a.gM)+(" starting on "+(g.H(a.hM)+". Cancel any time.")),b+='<div class="_mko"><h1>'+
c+"</h1></div>");c=b;u=a.no.eK;d=a.no.fK;f=a.UQ;k=a.lS;e=a.aI;l=a.qh;p=a.Iz;b="";a=a.no.dK?"<p>"+(0,g.I)("This title will be available to watch as many times as you like, in your account under Purchases. It does not expire.")+"</p>":"";a=b+('<div class="_mqo">'+a);u&&(u=(0,g.I)("You'll be charged at the start of every billing period. Cancel anytime. No refunds or credits for partial billing periods."),a=a+("<p>"+u+' <a href="#" '+g.L((0,g.ui)(k))+">Details</a></p><div "+g.L(g.P("ypcTermDetails"))+
' class="_mro" style="display: none;"><p>'),l?(k="Playback: You must have an Internet connection to stream video or take them offline. "+('<a href="'+g.K(g.jf(p))+'" target="_blank">Supported devices</a>'),a+=k):a+="Playback: You must have an Internet connection to stream video.",f="</p><p>For more information about the nature of this channel content, such as the intended audience and available languages, visit the channel's About section. Please be aware that information about the channel may not be in your native language.</p><p><a href=\""+
g.K(g.jf(f))+'" target="_blank">',k=(0,g.I)("Refund policy"),a=a+(f+k+"</a></p></div>"),e&&(a+="<p>",e='Based on your current account settings, this subscription will be shared publicly. You can change this by adjusting "Likes and Subscriptions" in your '+('<a href="'+g.K(g.jf("//www.youtube.com/account_privacy"))+'" target="_blank">privacy settings</a>.'),a+=e+"</p><br>"));d&&(a+="<h3>Rental information</h3><p>"+(0,g.I)("You will have  to start watching this content. Once started, you have  of viewing time.")+
"</p><br>");a+=g.J(g.rj({sa:(0,g.ch)("Help"),Ee:(0,g.dn)("//support.google.com/youtube?p=mweb_transact_help"),mM:!0}))+"</div>";a=(0,g.I)(a);return(0,g.I)(c+a)};
var xya=function(a){var b="";if(a.hf.cy||a.hf.Vq){if(a.hf.Vq)b+=g.H(a.hf.Vq);else{var c=a.hf.CI;if(a.hf.tL)var d="",c=g.Vo(new g.To("{COUNT_1,plural,=0{}=1{First 1 day free}other{First {COUNT_2} days free}}"),{COUNT_1:c,COUNT_2:g.H(c)}),c=(0,g.I)(d+c);else a.hf.uL?(d="",c=g.Vo(new g.To("{COUNT_1,plural,=0{}=1{First 1 month free}other{First {COUNT_2} months free}}"),{COUNT_1:c,COUNT_2:g.H(c)}),c=(0,g.I)(d+c)):a.hf.vL?(d="",c=g.Vo(new g.To("{COUNT_1,plural,=0{}=1{First 1 year free}other{First {COUNT_2} years free}}"),
{COUNT_1:c,COUNT_2:g.H(c)}),c=(0,g.I)(d+c)):c="";b=b+c}b+=a.Vy&&!a.qh?" &bull; ":""}return(0,g.I)(b)};var I9=function(a){g.Uv.call(this,"offer_details",a,wya)};var yya=function(a,b){return{sM:(0,g.M)(b.offer_group_list,function(a){return zya(this,a)},a),eK:b.has_recurring_offer,dK:b.has_purchase_offer,fK:b.has_rental_offer}};
var zya=function(a,b){var c=(0,g.M)(b.offer_summary_list,function(a){return{cy:a.has_free_trial,CI:a.free_trial_duration_count,tL:a.is_free_trial_in_days,uL:a.is_free_trial_in_months,vL:a.is_free_trial_in_years,Um:a.display_price,Mz:a.offer_id,Uy:a.is_ads_free,wL:a.is_hd,AL:a.is_rental,zL:a.is_purchase,N1:a.purchase_duration,A1:a.playback_duration,az:a.is_recurring,Wy:a.is_daily,Xy:a.is_monthly,bz:a.is_yearly,kx:a.coupon_code,Vq:a.coupon_free_trial_text,Ks:a.is_package,Yy:a.is_music_content_type,
ez:a.item_id,CL:a.item_type}},a);return{fz:Aya(b.item_offer_summary),Nz:c}};var Aya=function(a){return{title:a.title,subtitle:a.subtitle,Dx:a.entity_url,gS:a.thumbnail_url,v0:a.is_movie,u0:a.is_episode,x0:a.is_show_season,Ks:a.is_package,z0:a.is_video_type,BL:a.is_user_channel_type,w0:a.is_set_type,yL:a.is_music_type,Yy:a.is_music_content_type,rQ:a.package_channel_count}};var J9=function(a){g.Uv.call(this,"paid_unsubscribe_confirmation",a,yxa)};
var Bya=function(a){return{title:a.title,tr:a.external_id,Qs:a.logo_url}};
var Cya=function(a){var b=g.I,c,d="";c="Thank you! A receipt has been sent to "+(g.H(a.HC)+".");d+="<form "+g.L(g.vi("onsubmit",a.UN))+g.L(g.P("subscribeForm"))+'><div class="_mth"><div class="_muh">Purchase Complete</div></div><div class="_mne">';if(a.Yh){var e;e="<ul>";a=a.Yh;for(var f=a.length,k=0;k<f;k++){var l=a[k];e+='<label class="_mze"><img src="'+g.K(g.pf(l.Qs))+'" class="_mto"/><input type="checkbox" checked="checked" name="'+g.K(l.tr)+'" value="'+g.K(l.tr)+'"/>'+g.H(l.title)+"</label>"}e=
(0,g.I)(e+"</ul>");d=d+("<h2>These channels will be added to your guide</h2><hr />"+e+g.J(g.qj({sa:(0,g.ch)("Done"),bb:!0,type:"submit"})))}c=(0,g.I)(d+("<p>"+c+"</p></div></form>"));return b(c)};var K9=function(a){g.Uv.call(this,"post_purchase_confirmation",a,Cya);this.Ax=this.HC=this.Pb=this.Ve="";this.Yh=[]};var Dya=function(a){return{title:a.title,tr:a.external_id,Qs:a.logo_url}};var Eya=function(a){return(0,g.I)('<div class="_mri _mtt">'+g.J(g.N(a.hg))+"</div>")};
var L9=function(a){g.dB.call(this,"subscription_manager",a,Eya);a=this.hg=new g.WA((0,g.x)(this.cD,this));var b;b=(0,g.I)("You haven't added any subscriptions yet.");a.Yi=[b];a=this.hg;b=(0,g.I)("Show more subscriptions");a.ig=b;a=g.I;b=(0,g.I)("My subscriptions");this.Ib=a(b);a=(0,g.I)("Manage subscriptions");g.dA(this,a)};
var Fya=function(a){return(0,g.I)('<div class="_mihb"><div class="_mjhb"><div class="_mkhb">'+g.J(g.Kp({size:60,Tc:a.Nl.url}))+'<div class="_mlhb _mmhb"><img height="16" width="16" src="'+g.K(g.pf(g.Jh))+'" /></div></div>'+g.H(a.fS)+"<p>"+g.H(a.eS)+'</p><h1 class="_mnhb">'+g.H(a.Qq)+"</h1><p>"+g.H(a.Pq)+"</p>"+g.J(g.rj({Ee:a.Ve,sa:(0,g.ch)(" "+g.H(a.fq)+" "),bb:!0}))+"</div></div>")};
var Gya=function(a){return(0,g.I)('<div class="_mihb"><iframe src="'+g.K(g.jf(a.Ax))+'" class="_mohb"></iframe><div class="_mjhb"><div class="_mkhb">'+g.J(g.Kp({size:60,Tc:a.Nl.url}))+'<div class="_mlhb _mmhb"><img height="16" width="16" src="'+g.K(g.pf(g.Jh))+'" /></div></div><h1 class="_mnhb">'+g.H(a.Qq)+"</h1><p>"+g.H(a.Pq)+"</p>"+g.J(g.rj({Ee:a.Ve,sa:(0,g.ch)(" "+g.H(a.fq)+" "),bb:!0}))+"</div></div>")};
var Hya=function(a,b){g.T.call(this,a,Fya);this.fq=g.V(b.acknowledgement_text);this.Pq=g.V(b.confirmation_message);this.Qq=g.V(b.confirmation_message_header);this.Ve=b.continue_url;this.eS=g.V(b.thank_you_message);this.fS=g.V(b.thank_you_message_header);this.Nl=(0,g.qr)(b.viewer_thumbnail)};
var Iya=function(a,b){g.T.call(this,a,Gya);this.fq=g.V(b.acknowledgement_text);this.Pq=g.V(b.confirmation_message);this.Qq=g.V(b.confirmation_message_header);this.Ve=b.continue_url;this.Ax=b.embed_url;this.Nl=(0,g.qr)(b.viewer_thumbnail)};var Jya=function(a){return(0,g.I)(g.J(g.N(a.Do)))};var Kya=function(a,b){g.T.call(this,a,Jya);this.Do=g.Uq(this,b.post_tip_screen)};
var Lya=function(a){var b=g.I,c='<div class="_mihb">'+(a.Ww.url?(0,g.I)('<div class="_mxw"><div class="_myw"><img src="'+g.K(g.pf(a.Ww.url))+'"/><span class="_mzw"></span></div></div>'):""),d;d=(0,g.I)('<div class="_mkhb">'+g.J(g.Kp({size:60,Tc:a.Nl.url}))+(a.icon?'<div class="_mlhb">'+g.J(g.N(a.icon))+"</div>":"")+g.J(g.Kp({size:60,Tc:a.Xh.url}))+"</div>");c=c+d+'<div class="_mjhb"><h1 class="_mphb">'+g.H(a.nb)+'</h1><div class="_mqhb"><div class="_mrhb"'+g.L((0,g.ui)(a.uA,!1))+g.L((0,g.O)(""))+
'>-</div><div class="_mshb">'+g.J(g.xi("inputs",Mya))+'</div><div class="_mrhb"'+g.L((0,g.ui)(a.uA,!0))+g.L((0,g.O)(""))+">+</div></div>"+(a.Nj?"<p>"+g.H(a.Nj)+"</p>":"");d="";if(a.$h.lx){var e;e=g.bf("_mwhb");var f;f=g.bf("_mxhb");d+='<div class="_mxhb" '+g.L(g.P("commentInputContainer"))+'><p><a href="#"'+g.L((0,g.ui)(a.Bh,"commentInputContainer",e,f))+g.L((0,g.O)(""))+">"+g.H(a.$h.BH)+'</a></p><div class="_myhb"><div class="_mxi">'+g.J(g.Kp({size:g.zf?53:36,Tc:g.ym}))+'</div><div class="_myi"><input class="_mzi"'+
g.L(g.P("commentInput"))+'name="comment" type="text" placeholder= "'+g.K(a.$h.AH.zH)+'" /></div>'+(a.$h.fx?"<p>"+g.H(a.$h.fx)+"</p>":"")+"</div></div>"}d=(0,g.I)(d);return b(c+d+Nya({Pg:a.Nm,ob:"purchase"})+Nya({Pg:a.Qg,ob:"cancel"})+"</div></div>")};var Nya=function(a){return(0,g.I)(g.J(g.pj({Ng:a.Pg.Ch,Hb:a.Pg.Hb,ia:a.Pg.Ge,sa:a.Pg.text,bb:a.Pg.bb,style:a.Pg.style,ob:a.ob})))};
var Mya=function(a){return(0,g.I)(a.Ly?'<input type="tel" value="'+g.K(a.Ne)+'" class="_mthb"'+g.L(g.P("tipJarInput"))+g.L(g.vi("onblur",a.ro,!1))+" />":'<span class="_muhb _mwe"'+g.L(g.P("tipJarValue"))+" "+g.L((0,g.ui)(a.ro,!0))+g.L((0,g.O)(""))+">"+(a.qx?'<span class="_mvhb">'+g.H(a.ox)+"</span>":"")+g.H(a.Ne)+(a.qx?"":'<span class="_mvhb">'+g.H(a.ox)+"</span>")+"</span>")};
var M9=function(a,b,c,d){g.T.call(this,a,Lya);this.$h=new Oya(b.comment_data);this.g=new Pya(b.tip_data);this.Qg=g.Uq(this,b.cancel_button);this.Nm=g.Uq(this,b.confirmation_button);this.Nm.Ge=(0,g.x)(this.G,this);this.Nm.style="_mqc";this.Nm.bb=!0;this.Qg.Ge=function(){g.Si(c)};this.Qg.bb=!0;this.Nl=(0,g.qr)(b.viewer_thumbnail);this.Xh=(0,g.qr)(b.channel_thumbnail);this.icon=new g.av(this,b.icon);this.Ww=(0,g.qr)(b.channel_banner);this.nb=g.V(b.header);this.Nj=null;b.additional_info&&(this.Nj=g.V(b.additional_info));
this.Ou=b.tip_params;this.L=d;this.Ve=c;a=this.g.Qm;this.ox=g.Ae[a][1];this.qx=0==(g.Ae[a][0]&16);this.Ly=!1;this.C=this.g.g/1E6;this.Ne=this.g.b/1E6};var Pya=function(a){this.b=a.tip_amount_micros;this.Qm=a.currency_code;this.g=a.step_size_micros};var Oya=function(a){this.BH=g.V(a.comment_label_before);this.fx=g.V(a.comment_label_after);this.AH=new Qya(a.comment_entry_dialog);this.lx=a.create_comment_params||""};
var Qya=function(a){this.title=g.gr(a.title);this.zH=g.gr(a.comment_box_text);g.gr(a.cancel_text);g.gr(a.save_text)};var Rya=function(a){return(0,g.I)(a.Do?g.J(g.N(a.Do)):g.J(g.N(a.iS)))};var N9=function(a){g.Uv.call(this,"fanfunding",a,Rya);this.Ve="";this.g=a.it;this.b=a.ii};var Q8;g.y(R8,g.Vv);R8.prototype.la=function(a){this.$f=a.next_url;var b=this.Rx(a)||[];g.Ia(this.b,b);this.rg=this.Fa=!1;return R8.K.la.call(this,a)};
R8.prototype.Ec=function(a){"list"==a&&txa(this);return R8.K.Ec.call(this,a)};R8.prototype.Sl=function(a){this.b=[];R8.K.Sl.call(this,a)};R8.prototype.lt=function(){this.$f&&!this.rg&&(uxa(this,this.$f),this.rg=!0,g.Q(this,"paginator"))};g.y(zxa,g.wj);g.y(T8,g.Uv);T8.prototype.he="yt_setting";
T8.prototype.la=function(a){var b=[];b.d=g.GA();b.w=g.HA();b.n=S8();this.ue=a.digest_frequency;this.Tm=b[a.digest_frequency];this.av=a.video_distiller_enabled;this.g=a.dasher_disabled;this.wn=a.google_plus_setting_link;b=(0,g.I)("YouTube live event");this.Le=[U8("email_live_events",b,a)];var b=(0,g.I)("Subscription to my channel"),b=U8("email_subscriber",b,a),c;c=(0,g.I)("Comment on my channel");c=U8("email_profile",c,a);var d;d=(0,g.I)("Comment or response on my video");d=U8("email_comments",d,a);
var e;e=(0,g.I)("Private message or shared video");e=U8("email_contact",e,a);var f;f=(0,g.I)("Upload finished");f=U8("email_upload_notification",f,a);var k;k=(0,g.I)("Community actions require attention");this.Cd=[b,c,d,e,f,U8("email_community_actions",k,a)];!this.g&&this.av&&(b=this.Cd[2],c=(0,g.I)("Comments on private videos"),b.name=c);""!=this.wn&&this.Cd.splice(1,1);b=(0,g.I)("Trending videos, hot music, and announcements");b=U8("email_marketing_newsletter",b,a);c=(0,g.I)("Tips and news for creators (including Creator Pulse email)");
this.Fe=[b,U8("email_creator_newsletter",c,a)];b=[];for(c=0;c<a.supported_email_locales.length;c+=1)b[a.supported_email_locales[c][0]]=a.supported_email_locales[c][1];this.mr=b[a.email_locale];this.zx=g.Lo(this.mr)?"rtl":"ltr";this.xsrf_token=a.xsrf_token;this.Fa=!1;return T8.K.la.call(this,a)};
T8.prototype.lf=function(a){for(var b=0;b<this.Le.length;b+=1)a==this.Le[b].xc&&(this.Le[b].enabled=!this.Le[b].enabled,V8(this,a,this.Le[b].enabled));for(b=0;b<this.Cd.length;b+=1)a==this.Cd[b].xc&&(this.Cd[b].enabled=!this.Cd[b].enabled,V8(this,a,this.Cd[b].enabled));for(b=0;b<this.Fe.length;b+=1)a==this.Fe[b].xc&&(this.Fe[b].enabled=!this.Fe[b].enabled,V8(this,a,this.Fe[b].enabled))};
T8.prototype.FN=function(){for(var a=this.Y("notificationsForm"),b=(0,g.x)(function(a){this.b--;this.b||g.Zn(this,!1);g.Q(this);g.Qi(g.Ui(a))},this),c=0;c<this.Le.length;c+=1)this.Le[c].enabled=!1,a.elements[this.Le[c].xc].value=!1;for(c=0;c<this.Cd.length;c+=1)this.Cd[c].enabled=!1,a.elements[this.Cd[c].xc].value=!1;for(c=0;c<this.Fe.length;c+=1)this.Fe[c].enabled=!1,a.elements[this.Fe[c].xc].value=!1;this.ue="n";this.Tm=S8();a.elements.digest_frequency.value="n";a.elements.block_emails.value=!0;
g.wA(a,b,g.sp);g.Zn(this,!0);this.b++};g.y(W8,g.Uv);W8.prototype.he="yt_setting";W8.prototype.la=function(a){this.xsrf_token=a.xsrf_token;this.g=a.digest_frequency;Ixa(this);this.Fa=!1;return W8.K.la.call(this,a)};W8.prototype.hR=function(){var a=this.Y("frequencyForm"),b=(0,g.x)(function(a){this.b--;this.b||g.Zn(this,!1);g.Qi(g.Ui(a))},this);g.wA(a,b,g.sp);g.Zn(this,!0);this.b++};g.y(X8,g.Uv);X8.prototype.he="yt_setting";
X8.prototype.la=function(a){this.xsrf_token=a.xsrf_token;this.g=a.email_locale;Jxa(this,a.supported_email_locales);this.Fa=!1;return X8.K.la.call(this,a)};X8.prototype.gR=function(){var a=this.Y("emailLocaleForm"),b=(0,g.x)(function(a){this.b--;this.b||g.Zn(this,!1);g.Qi(g.Ui(a))},this);g.wA(a,b,g.sp);g.Zn(this,!0);this.b++};g.Hk("account_notifications",function(a){return"action_digest_frequency"in a?new W8:"action_email_locale"in a?new X8:new T8});g.y(Y8,g.Uv);Y8.prototype.o=function(a){var b=this.Y("privacyForm");b.elements.updated_element.value=a;g.wA(b,(0,g.x)(this.B,this),g.sp);g.Zn(this,!0);this.b++};Y8.prototype.B=function(a){this.b--;this.b||(g.Ti(a)?(this.la(this.g),g.Qi(g.Ti(a))):(this.la(a.content),g.Qi(g.Ui(a))),g.Q(this),g.Zn(this,!1))};
Y8.prototype.la=function(a){this.Pb=a.xsrf_token;var b=(0,g.I)("Likes and Subscriptions"),c;c=(0,g.I)("Keep all my Liked Videos and Liked Playlists private");c=new g.hD("not_discoverable_likes",c,!a.discoverable_likes,this.o);var d;d=(0,g.I)("Keep all my subscriptions private");this.VB=[new g.gD(b,[c,new g.hD("not_discoverable_subscriptions",d,!a.discoverable_subscriptions,this.o)])];this.Fa=!1;this.g=a;return!0};g.Hk("account_privacy",Y8);g.y($8,g.Uv);g.ca($8);$8.prototype.la=function(a){this.Fa=!1;this.uk=a.identity_revert_label;this.jc=a.public_name;this.xsrf_token=a.xsrf_token;this.Td=a.youtube_name;return $8.K.la.call(this,a)};g.y(a9,g.Uv);g.ca(a9);a9.prototype.la=function(a){this.Fa=!1;this.pB=a.profile_url;this.Td=a.youtube_name;return a9.K.la.call(this,a)};g.y(b9,g.Uv);g.ca(b9);
b9.prototype.la=function(a){this.Fa=!1;this.uk=a.identity_revert_label;this.jc=a.public_name;this.xsrf_token=a.xsrf_token;this.Td=a.youtube_name;return b9.K.la.call(this,a)};g.y(c9,g.Uv);g.ca(c9);c9.prototype.la=function(a){this.Fa=!1;this.jc=a.public_name;this.xsrf_token=a.xsrf_token;this.Td=a.youtube_name;return c9.K.la.call(this,a)};g.y(d9,g.Uv);g.ca(d9);
d9.prototype.la=function(a){this.Fa=!1;this.xsrf_token=a.xsrf_token;this.WG=a.authorized_sites_url;this.HH=a.contacts_url;this.IL=a.learn_more_local_reviews_url;this.JL=a.learn_more_page_transfer_url;this.KL=a.learn_more_pages_you_manage_url;this.Hu=!0;this.BC=!1;return d9.K.la.call(this,a)};d9.prototype.CP=function(){this.Hu=!this.Y("acceptCheckbox").checked;this.BC=this.Y("unfollowCheckbox").checked;g.Q(this)};
g.Gk.account_revert=function(a){var b=null;if("action_explain"in a)switch(a.ver){case "3R":b=d9.Oa()}else if("action_done"in a)switch(a.ver){case "3R":b=c9.Oa();break;default:b=a9.Oa()}else switch(a.ver){case "3R":b=b9.Oa();break;default:b=$8.Oa()}return b};g.y(e9,g.Uv);e9.prototype.la=function(a){e9.K.la.call(this,a);a.user_list&&(this.$u=(0,g.M)(a.user_list,function(a){return new Yxa(a.account_name,a.gaia_email,a.thumbnail,a.switcher_url,a.is_selected,a.is_parent,a.create_plus_page_url)}));this.Aw=a.add_account_url;this.pj=a.signout_options_url;this.Dn=a.hide_signout;this.Fa=!1;return!0};g.Hk("channel_switcher",e9);var Sya=/Mac OS X.+Silk\//,Tya=/OS (\d)_(\d)(?:_(\d))?/,gya=/Chrome\/([0-9.]+)/;var O9=/iPhone|iPod|iPad/.test(window.navigator.userAgent)||g.ua(window.navigator.userAgent,"Android")||Sya.test(window.navigator.userAgent),i9=window.navigator.msPointerEnabled,Uya=O9?"touchstart":i9?"MSPointerDown":"mousedown",Vya=O9?"touchmove":i9?"MSPointerMove":"mousemove",eya=O9?"touchend":i9?"MSPointerUp":"mouseup",Wya=i9?"MSPointerCancel":"touchcancel";var k9,iya,l9,P9;m9.prototype.b=0;m9.prototype.Bt=function(a){if(!this.F&&this.b!=this.o){for(var b=h9(a),c=Math.min(b.length,this.o-this.b),d=0;d<c;d++){var e=b[d];this.g[this.b]=j9(e);this.C[this.b]=e.clientX;this.D[this.b]=e.clientY;this.b++}n9(this,a);if(this.b==this.o)for(d=0;d<this.o;d++)this.G[d]=this.H[d]=0;this.W(a)}};m9.prototype.yo=function(a){if(!this.F&&0<this.b&&n9(this,a)){this.A&&this.M(a);a=this.b;for(var b=0,c=0;c<a;c++)this.B[c]&&(this.g.splice(c-b,1),this.b--,this.A=!1,b++)}};
m9.prototype.reset=function(){this.b=0;this.F=this.A=!1};g.y(o9,m9);o9.prototype.W=function(a){var b=this.J,c=this.C[0],d=this.D[0];a=a.timeStamp;b.b.length=b.g.length=0;b.b.push(c,a);b.g.push(d,a)};
o9.prototype.S=function(a){var b=this.L;a.preventDefault();var c=b.ve,b=b.cI;y9(c);c.$j=b;var d=b.cloneNode(!0);c.A&&g.Fc(d,c.A);d.style.margin="0";d.style.position="absolute";d.style.visibility="hidden";g.dc(b).body.appendChild(d);g.oq(d,b.offsetLeft,b.offsetTop);d.style.visibility="";d.b=a.touches[0].pageY-b.offsetTop;c.b=d;b.style.visibility="hidden";for(var d=g.uc(c.ve),e=0,f=!1;e<d.length;e++){var k=d[e];k==b?(delete k.Nw,f=!0):k.Nw=f?k.offsetTop:d[e+1].offsetTop-1}g.Th(window.document,r9,c,
a);return!0};o9.prototype.O=function(a){var b=this.J,c=kya(this),d=lya(this),e=a.timeStamp,f=b.b[b.b.length-2]-c,k=b.g[b.g.length-2]-d,l=b.b,p=b.o;p&&f&&2<l.length&&0<p^0<f&&l.splice(0,l.length-2);l=b.g;(p=b.A)&&k&&2<l.length&&0<p^0<k&&l.splice(0,l.length-2);f9(b.b,e);f9(b.g,e);b.b.push(c,e);b.g.push(d,e);b.o=f;b.A=k;b=this.L;a.preventDefault();qya(b.ve,a.touches[0].pageY,a);a.preventDefault()};
o9.prototype.M=function(a){if(a){var b=this.J,c=this.R[this.g[0]],d=a.timeStamp;g.n(this.N[this.g[0]])&&g.n(c)&&d&&(f9(b.b,d),f9(b.g,d));a.preventDefault()}b=this.L;a.preventDefault();b=b.ve;y9(b);g.Th(window.document,t9,b,a);b=this.C[0];c=this.D[0];if(d=a)g.n(P9)||(d=Tya.exec(window.navigator.userAgent)||[],d.shift(),P9=dya.apply(null,d)>=dya(6)||!1),d=P9;if(d)a.preventDefault();else for(l9=void 0,k9||(window.document.addEventListener("click",hya,!0),a=jya,O9||i9||(a=g9(a)),g.Sh(window.document,
Uya,a,!0,!0),k9=[]),iya=(0,g.G)(),a=0;a<k9.length;a+=2)if(25>Math.abs(b-k9[a])&&25>Math.abs(c-k9[a+1])){k9.splice(a,a+2);break}};g.y(p9,m9);p9.prototype.W=g.w;p9.prototype.S=function(a){return this.J.o(a)};p9.prototype.O=function(a){this.J.g(a);a.preventDefault()};p9.prototype.M=function(a){this.J.b(a);a&&a.preventDefault()};var pya=[o9,p9];g.h=q9.prototype;g.h.vP=function(a){var b=a.touches||[a],c=b.length,d;for(d in this.g){for(var e=0;e<c;e++)if(d==j9(b[e])){var f=!0;break}f||mya(this,+d)}b=h9(a);c=b.length;for(e=0;e<c;e++)d=j9(b[e]),g.n(this.g[d])&&mya(this,+d);c=!0;e=this.b.length;for(b=0;b<e;b++)if((d=this.b[b])&&d.b!=d.o){c=!1;break}if(!c&&this.A.Bt(a)){c=h9(a);d=c.length;for(b=0;b<d;b++){var f=c[b],k=j9(f);this.g[k]=f.clientX;this.o[k]=f.clientY}for(b=0;b<e;b++)(d=this.b[b])&&d.Bt(a)}};
g.h.uO=function(a){for(var b=!0,c=this.b.length,d=0;d<c;d++){var e=this.b[d];if(e&&0<e.b){b=!1;break}}if(!b){for(d=0;d<c;d++)if(e=this.b[d])if(b=e,e=a,!b.F&&b.b==b.o&&n9(b,e))if(b.A)b.O(e);else{for(var f=void 0,k=0;k<b.o;k++){var l=b.B[k];if(l){var p=b.g[k],u=b.R[p]-l.clientY;b.G[k]+=Math.abs(b.N[p]-l.clientX);b.H[k]+=Math.abs(u);f=f||2<b.G[k]||2<b.H[k]}}if(f){for(k=0;k<b.o;k++)b.C[k]=kya(b,k),b.D[k]=lya(b,k);b.A=b.S(e);b.A?b.O(e):b.reset()}}a=h9(a);c=a.length;for(d=0;d<c;d++)b=a[d],e=j9(b),g.n(this.g[e])&&
(this.g[e]=b.clientX,this.o[e]=b.clientY)}};g.h.kt=function(a){for(var b=h9(a),c=b.length,d,e=0;e<c;e++){var f=b[e],f=j9(f);g.n(this.g[f])&&(this.A.yo(a),d=!0)}if(d){d=this.b.length;for(e=0;e<d;e++)(f=this.b[e])&&f.yo(a);for(e=0;e<c;e++)f=b[e],f=j9(f),g.n(this.g[f])&&(delete this.g[f],delete this.o[f])}};
g.h.enable=function(a,b){var c=(0,g.x)(this.kt,this),d=this.B,e=(0,g.x)(this.vP,this),f=(0,g.x)(this.uO,this),k=c;O9||i9||(e=g9(e),f=g9(f),k=g9(k));var l=!!a;g.Sh(d,Uya,e,l,b);g.Sh(d,Vya,f,l,b);g.Sh(d,eya,k,l,b);g.Sh(d,Wya,c,l,b)};g.h.reset=function(){for(var a in this.g)delete this.g[Number(a)],delete this.o[Number(a)];for(a=0;a<this.b.length;a++){var b=this.b[a];b&&b.reset()}};g.h=nya.prototype;g.h.fT=function(){var a=this.g;if(a&&(0>a||g.El.Nc.fd()+g.ci()<this.C)){var b=g.El.Nc;b.ne(b.fd()+12*a);a=this.ve;qya(a,a.C+(g.El.Nc.fd()-a.g))}};g.h.eT=function(){u9(this);this.C=window.document.height;this.b=window.setInterval((0,g.x)(this.fT,this),40)};g.h.dT=function(a){(a=a.Fx)&&a.touches&&(a=a.touches[0].pageY-g.El.Nc.fd(),this.g=40>a?-1:g.ci()-40<a?1:0)};g.h.cT=function(){u9(this)};
g.h.dispose=function(){u9(this);window.document.removeEventListener(r9,this.B,!1);window.document.removeEventListener(s9,this.A,!1);window.document.removeEventListener(t9,this.o,!1)};v9.prototype=new function(){};v9.prototype.Y=function(){return this.pJ};v9.prototype.Bt=function(a){a.preventDefault();return!0};v9.prototype.yo=g.w;g.y(x9,q9);x9.prototype.kt=function(a){"touchmove"!=a.type&&x9.K.kt.call(this,a)};
w9.prototype.init=function(){for(var a=g.uc(this.ve),b=0,c=a.length;b<c;b++){var d=new v9(this,a[b],this.B(a[b])),d=new x9(d);this.o.push(d)}};w9.prototype.dispose=function(){y9(this);for(var a=0;a<this.o.length;a++)delete this.o[a];this.D.dispose()};var r9="dragstart_"+g.pn++,s9="dragmove_"+g.pn++,t9="dragend_"+g.pn++;g.y(z9,R8);g.h=z9.prototype;g.h.ne=function(a){if(this.Be)window.scroll(0,a);else return z9.K.ne.call(this,a)};g.h.fd=function(){return this.Be?window.pageYOffset:z9.K.fd.call(this)};g.h.la=function(a){z9.K.la.call(this,a);this.zk=0<this.b.length;this.Is=!g.zf&&this.zk&&!1;return!0};g.h.za=function(a){z9.K.za.call(this);var b=this.Y("list");b&&g.wc(this.Y(a),b)&&rya(this)};g.h.jt=function(){this.g&&y9(this.g);sya(this,!this.Be)};g.h.bN=function(){A9(this)};
g.h.hP=function(a){var b=this.Y("form"),c=g.he(b);this.sendRequest(b.getAttribute("action"),g.te(c),(0,g.x)(this.fP,this,a));this.bp=!0;this.nd()};g.h.fP=function(a,b){this.bp=!1;g.Ti(b)?this.IA(a,b):(this.b[a]=this.Tx(b.content),A9(this))};g.h.eP=function(){var a=this.Y("form"),b=g.he(a);this.sendRequest(a.getAttribute("action"),g.te(b),(0,g.x)(this.DM,this));this.bp=!0;this.nd()};g.h.Mo=function(a){this.b.splice(a,1);g.Q(this,"list")};
g.h.sendRequest=function(a,b,c){"session_token"in b||(b.session_token=this.o);a=new g.bj(g.wf(a),b,!0);g.$n(a,c);c=(0,g.x)(this.Zs,this);a.g.push(c);c=g.x(g.Si,this);a.b=c;a.send();g.E(this,a)};g.h.hT=function(a){var b=a.sender.$j;a=(0,window.parseInt)(b.getAttribute("data-index"),10);var c=g.gc("_mhb",this.Y("list")),b=(0,g.Ca)(c,b);a!=b&&null(a,b)};g.h.Aa=function(){sya(this,!1);this.g&&(this.g.dispose(),this.g=null);this.B&&window.document.removeEventListener(t9,this.B,!1);z9.K.Aa.call(this)};
g.y(D9,z9);D9.prototype.Rx=function(a){return g.ar(a.videos)};D9.prototype.bD=function(a,b){var c=this.Md(g.Mq,{video:a,index:b,ci:this.Be});return this.Md(Zxa,{hx:c,index:b})};g.y(E9,D9);E9.prototype.gi=function(){return(0,g.I)("Favorites")};E9.prototype.la=function(a){this.o=a.manage_favorites_xsrf_token;return E9.K.la.call(this,a)};E9.prototype.aj=function(a){this.sendRequest("/manage_favorites?action_delete=1",{v:this.b[a].sb},(0,g.x)(this.Mo,this,a));B9(this,a)};(function(a,b,c,d){g.Fk(a,function(e,f,k){f=new d(e,f,k);return new g.Ok(a,e,k,[b],c,f)})})("my_favorites","mobile_blazer_logged_in_users_mod",!1,E9);g.y(F9,D9);F9.prototype.gi=g.zA;F9.prototype.la=function(a){this.o=a.xsrf_token;F9.K.la.call(this,a);g.dA(this,g.zA());this.zk=0<this.b.length;return!0};F9.prototype.aj=function(a){this.sendRequest("/my_history?action_delete_history_entries=1",{video_ids:this.b[a].sb},(0,g.x)(this.Mo,this,a));B9(this,a)};g.Hk("my_history",F9);g.y(G9,z9);g.h=G9.prototype;g.h.gi=Dxa;g.h.xx=uya;g.h.eI=uya;g.h.Rx=function(a){return(a=a.playlists)&&(0,g.M)(a,P8)};g.h.bD=function(a,b){var c={hx:this.Md(sxa,{fl:a,index:b,ci:this.Be}),index:b};vya(a.type)&&(c.to=null,c.aj=null);return this.Md(Zxa,c)};g.h.la=function(a){this.o=a.manage_playlist_xsrf_token;return G9.K.la.call(this,a)};g.h.aj=function(a){this.sendRequest("/manage_playlist?action_delete_playlist=1",{p:this.b[a].sb},(0,g.x)(this.Mo,this,a));B9(this,a)};
g.h.to=function(a){C9(this,this.b[a],a)};g.h.Tx=function(a){return P8(a.playlist)};g.h.IA=function(a,b){g.Qi(g.Ti(b),!0);C9(this,this.b[a],a)};g.h.Vz=function(){tya(this)};g.h.DM=function(a){this.bp=!1;if(g.Ti(a))g.Qi(g.Ti(a),!0),tya(this);else{A9(this);a=P8(a.content.playlist);for(var b=0;vya(this.b[b].type);)b+=1;b||(b=0);this.b.splice(b,0,a);g.Q(this,"list")}};g.Jk.manage_playlist=new g.vA("my_playlists");g.Hk("my_playlists",G9);g.y(H9,D9);g.h=H9.prototype;g.h.he="yt_myvideos";g.h.gi=function(){var a=g.I,b;b=(0,g.I)("My videos");b='<div class="_mco">'+g.H(b)+'</div><div class="_mdo"><a href="//support.google.com/youtube/answer/57407?topic=1232419&ctx=topic">';var c;c=(0,g.I)("Learn more about uploading videos from your device");return a(b+g.H(c)+"</a></div>")};
g.h.xx=function(a){var b="",c='<div class="_mwn"><div class="_mrf">'+g.J(g.Hq(a.Mb))+'</div><input type="hidden" name="v" value="'+g.K(a.Mb.sb)+'"><div class="_mxn"><div class="_myn">Title</div><input type="text" name="field_myvideo_title" value="'+g.K(a.Mb.title)+'" class="_mbo"></div><div class="_mxn"><div class="_myn">Description</div><textarea name="field_myvideo_descr" rows="5" class="_mbo">'+Hxa(a.Mb.description)+'</textarea></div><div class="_mxn"><div class="_myn">Tags</div><input type="text" name="field_myvideo_keywords" value="'+
g.K(a.Mb.rC)+'" class="_mbo"></div><div class="_mxn"><div class="_myn">'+g.J(Fxa())+'</div><div class="_mue"><select class="_mve _mzn" name="field_privacy"><option value="public"'+("public"==a.Mb.privacy?'selected="selected"':"")+">"+g.J(g.Ro())+'</option><option value="unlisted"'+("unlisted"==a.Mb.privacy?'selected="selected"':"")+">",d;d=(0,g.I)("Unlisted");a=b+(c+g.H(d)+'</option><option value="private"'+("private"==a.Mb.privacy?'selected="selected"':"")+">"+g.J(g.Qo())+"</option></select></div></div></div>");
return(0,g.I)(a)};g.h.la=function(a){this.o=a.manage_video_xsrf_token;return H9.K.la.call(this,a)};g.h.aj=function(a){var b=this.b[a];g.zj(new zxa(b,(0,g.x)(this.VH,this,b,a)))};g.h.to=function(a){C9(this,this.b[a],a)};g.h.VH=function(a,b){this.sendRequest("/manage_videos?action_delete=1",{v:a.sb},(0,g.x)(this.Mo,this,b));B9(this,b)};g.h.Tx=function(a){return(0,g.br)(a.video)};
g.h.IA=function(a,b){g.Qi(g.Ti(b),!0);var c=g.tq(this.b[a]),d=b.content;c.description=d.description;c.privacy=d.privacy;c.rC=d.tags_formated;c.title=d.title;C9(this,c,a)};g.Hk("my_videos",H9);g.y(I9,g.Uv);g.h=I9.prototype;g.h.la=function(a){this.no=yya(this,a.offerGroups);this.b=a.inappJsUri;this.Pb=a.xsrfToken;this.UQ=a.refundPolicyUrl;this.aI=a.discoverableSubscriptions;this.itemId=a.itemId;this.Fa=!1;this.qh=a.isMusicSubscription;this.hM=a.musicKeyRecurrenceStartTime;this.Iz=a.musicKeySupportedDevicesUrl;this.eM=a.musicKeyOfferSummary;this.gM=a.musicKeyPriceWithUnit;this.Hz=a.musicKeyPlusPageWarning;this.fM=a.musicKeyPlusPageHelpMsg;return I9.K.la.call(this,a)};
g.h.DO=function(a){var b=new g.bj("transaction_handler",{action_request:1,session_token:this.Pb,oid:a.Mz,cc:a.kx},!0);g.E(this,b);g.$n(b,(0,g.x)(this.aR,this,a));b.g.push(this.Yk);b.b=g.sp;b.send();g.Jg({action:"ypc-checkout-mobile",label:"purchase-button-click"})};g.h.lS=function(){var a=this.Y("ypcTermDetails");"none"!=a.style.display?g.Cc(a,!1):g.Cc(a,!0)};
g.h.aR=function(a,b){var c=b.content;if(0==c.status){var d=c.cart_jwt;g.tk(this.b,(0,g.x)(function(){g.Jg({action:"ypc-checkout-mobile",label:"gb-start"});window.google.payments.inapp.buy({parameters:{locale:g.Sf,userSessionIndex:g.yk},jwt:d,success:(0,g.x)(this.sH,this,a),failure:(0,g.x)(this.Yk,this)})},this));g.Jg({action:"ypc-checkout-mobile",label:"flow-offers-init",jwt:d})}else this.Yk()};
g.h.sH=function(a,b){var c=new g.bj("transaction_handler",{action_register:1,ps:"C",session_token:this.Pb,oc:b.response.orderId,oid:a.Mz,cc:a.kx,eiid:a.ez,it:a.CL},!0);g.E(this,c);g.$n(c,(0,g.x)(this.gL,this,a));c.g.push(this.iT);c.b=g.sp;c.send();g.Jg({action:"ypc-checkout-mobile",label:"gb-success",orderId:b.response.orderId})};g.h.gL=function(a,b){switch(b.content.status){case 0:g.Qi([g.Np()]),a.Ks?g.Si("/post_purchase_confirmation?id="+a.ez):a.Yy?g.Si("/feed/music"):g.Si("/channel/"+this.itemId)}};
g.h.Yk=function(a){a&&"PURCHASE_CANCELED"==a.response.errorType||(g.Qi([g.Op()],!0),g.Jg({action:"ypc-checkout-mobile",label:"gb-failure"}))};g.h.iT=function(){g.Qi([g.Mp()],!0);g.Jg({action:"ypc-checkout-mobile",label:"gb-abort"})};g.Hk("offer_details",I9);g.y(J9,g.Uv);
J9.prototype.la=function(a){this.o=a.itemType;this.itemId=a.itemId;this.Pb=a.xsrfToken;this.Yh=(0,g.M)(a.channel_summaries,Bya);var b=a.channel_title,c=a.expiration_date_string;if(b&&c){if(a.is_package)if(a.is_free_channels_only_package)var d="",b="Your subscription to "+(g.H(b)+(" will end on "+(g.H(c)+" (the last day of the current billing cycle). After that date, we'll no longer charge your credit card for this subscription.")));else d="",b="Your subscription to "+(g.H(b)+(" will end on "+(g.H(c)+
" (the last day of the current billing cycle). After that date, we'll no longer charge your credit card for this subscription, and you'll no longer have access to the following channels:")));else d="",b="Your subscription to "+(g.H(b)+(" will end on "+(g.H(c)+" (the last day of the current billing cycle). After that date, we'll no longer charge your credit card for this subscription, and you'll no longer have access to this channel.")));b=(0,g.I)(d+b)}else b=(0,g.I)("Your subscription will be canceled when you unsubscribe. Your credit card will no longer be charged. You will still be able to access content until the billing cycle ends.");
this.vS=b;this.Fa=!1;return J9.K.la.call(this,a)};J9.prototype.OP=function(){var a=new g.bj("transaction_handler",{action_cancel:1,session_token:this.Pb,it:this.o,ii:this.itemId},!0);g.E(this,a);g.$n(a,(0,g.x)(this.g,this));a.g.push(this.b);a.b=g.sp;a.send()};J9.prototype.g=function(a){switch(a.content.status){case 0:g.Si("/channel/"+this.itemId);break;default:this.b()}};J9.prototype.b=function(){g.Qi([g.Nr()],!0)};g.Hk("paid_unsubscribe_confirmation",J9);g.y(K9,g.Uv);K9.prototype.la=function(a){this.HC=a.user_email;this.Yh=(0,g.M)(a.channel_summaries,Dya);this.Ve=a.continue_url;this.Pb=a.xsrf_token;this.Fa=!1;return K9.K.la.call(this,a)};K9.prototype.UN=function(){var a=this.Y("subscribeForm");(a=g.he(a))?(a=g.te(a),a=new g.bj("subscription_service",{action_subscribe:1,channel_ids:g.Ma(a).join(","),session_token:this.Pb},!0),g.E(this,a),g.$n(a,(0,g.x)(this.b,this)),a.g.push(this.g),a.b=g.sp,a.send()):g.Si(this.Ve)};
K9.prototype.b=function(a){"error"===a.result?g.Qi(g.Ti(a),!0):g.Si(this.Ve)};K9.prototype.g=function(){var a;a=(0,g.I)("Sorry, there was an error processing your request.");g.Qi([a],!0)};g.Hk("post_purchase_confirmation",K9);g.y(L9,g.dB);L9.prototype.g=function(a){var b=a.subscribe_xsrf_token;return(0,g.M)(a.subscriptions||[],function(a){a=g.sA(a);b&&a.kp&&(a.qf=g.YA(a.kp,b,a.jp.subscriber_count,a.jp,a.url));return a})};g.Hk("subscription_manager",L9);g.y(Hya,g.T);g.U.ypc_post_tip_text_screen=Hya;g.y(Iya,g.T);g.U.ypc_post_tip_embed_video_screen=Iya;g.y(Kya,g.T);g.y(M9,g.T);M9.prototype.ro=function(a){this.Ly=a;if(!a){var b;this.Y("tipJarInput")?(b=(0,window.parseInt)(this.Y("tipJarInput").value,10),b=!(0,window.isNaN)(b)&&0<b?b:this.g.b/1E6):b=this.Ne;this.Ne=b}g.Q(this,"inputs");a&&this.Y("tipJarInput").focus()};M9.prototype.uA=function(a){a?this.Ne+=this.C:0<this.Ne-this.C&&(this.Ne-=this.C);g.Q(this,"inputs")};
M9.prototype.G=function(){var a={RH:this.Ne,Ou:this.Ou,Qm:this.g.Qm};this.$h.lx&&this.Y("commentInput")&&(a.comment=this.Y("commentInput").value);this.L(a)};g.y(N9,g.Uv);N9.prototype.o=function(a){a.content.post_tip_screen&&(this.Do=new Kya(null,a.content),this.nd())};N9.prototype.la=function(a){var b=a.tip_screen,c=a.continue_url;this.Pb=a.xsrfToken;g.nd("YPC_GB_URL",a.inappJsUri);this.iS=new M9(null,b,c,(0,g.x)(this.B,this));this.Fa=!1;return N9.K.la.call(this,a)};
N9.prototype.B=function(a){var b;b={config:{couponCode:"",fromPurchaseIds:"",flowType:"T"},itemData:{itemId:this.b,itemType:this.g},offerData:{offerId:""}};var c=a.RH,d=a.comment;a={tipParams:a.Ou,currencyCode:a.Qm};c&&(a.customTipAmount=c);d&&(a.tipComment=d);g.Qa(b.config,{tipConfig:a});new g.Qr(b,this.Pb,(0,g.x)(this.o,this))};g.Hk("fanfunding",N9);})(_yt_m);
