(function(g){var window=this;var tz=function(a,b,c,d){this.element=a;this.g=b;this.b=c;this.Ue=!!d};var uz=function(a,b,c,d,e,f){d=g.Nh(b,c,d,e,f);a.b.push(new tz(b,c,d,e));return d};var vz=function(a,b,c,d,e){var f=new tz(b,c,d,!1);c=g.Nh(b,c,function(){f.element.removeEventListener(f.g,f.b,f.Ue);d.apply(b,arguments)},!1,e);f.b=c;a.b.push(f)};var wz=function(a,b){return null!=a&&null!=b?g.Vb(a,{signature:g.xo(b)}):a};var xz=function(a,b){for(var c=0;c<b.length;c++){var d=g.Yn(a,function(a){return a.itag==b[c]});if(d)return d}return null};
var yz=function(a){if(a){if(zga.exec(a))return"hls";a=Aga.exec(a);return!a||2>a.length?"":a[1]}return""};
var zz=function(a,b){this.D=this.o=this.g=this.A=this.C=0;this.b={};this.B=a;this.F=new g.Oh;g.E(this,this.F);this.C=Math.min(.8*b.gb,180);this.A=b.gb;this.b={html5:"1",app:"youtube_mobile",ps:"blazer",video_id:b.videoId,el:"detailpage",plid:b.H,cpn:b.Wa};var c=g.Fl();c&&(this.b.referrer=c.slice(0,128));b.subscribed&&(this.b.subscribed=b.subscribed);b.kb&&(this.b.list=b.kb);b.Bc&&(this.b.t=b.Bc);b.Vc&&(this.b.access_token=b.Vc);g.na(this.b,g.wm);this.G=uz(this.F,this.B,"timeupdate",(0,g.x)(this.H,
this),!1,"SetAwesome")};var Bga=function(a){var b="";a="Your video will follow this ad in "+(g.H(a.FG.duration)+" seconds");return(0,g.I)(b+('<div class="_mmp"><div>'+a+"</div></div>"))};
var Cga=function(a){return(0,g.I)('<div class="_mkp _mlp" style="width:'+g.K(g.qf(a.width))+"px;height:"+g.K(g.qf(a.height))+'px;"><OBJECT width="'+g.K(a.width)+'" height="'+g.K(a.height)+'"><param name="movie" value="'+g.K(a.url)+'"></param><param name="wmode" value="transparent"></param><embed src="'+g.K(g.jf(a.url))+'" type="application/x-shockwave-flash" wmode="transparent" width="'+g.K(a.width)+'" height="'+g.K(a.height)+'"></embed></OBJECT></div>')};
var Az=function(a,b){var c=null,d=null;if(a.fk){var e=Dga,f=xz(a.fk,Ega);f&&(d=wz(f.url,f.sig||f.s||null),g.Ba(e,f.itag)&&(e=g.Ha(e),g.Da(e,f.itag)));(e=xz(a.fk,e))&&(c=wz(e.url,e.sig||e.s||null));if(!c&&!d&&1==a.fk.length)return a.fk[0].url}return(g.n(b)?b:g.Mo())?d||c:c||d};var Fga=function(){return(0,g.I)("Failed to load the video stream.  Please try reloading the page.")};var Bz=function(a){return g.n(g.Pd.get(""+a))};var Cz=function(){g.My.call(this,Cga)};var Dz=function(a){g.Di.call(this,a)};
var Ez=function(a){a&&a.VL?a=!0:(null==Fz&&(Fz=(a=g.Kg("lastAdTime"))?g.xf(a):0),a=!Gga(Fz));return a};var Gz=function(a){this.b={};this.g=a};var Hz=function(a,b){this.S=new Gz(a);this.B={};this.H=b;this.A=null;this.M=new g.Oh;g.E(this,this.M)};
var Iz=function(a,b,c,d,e){Hz.call(this,a.Ru,a.duration);this.g=a;this.W=b;this.qe=a.UR;this.R=c;this.D=this.C=null;this.o=this.qe?0:3;this.J=this.G=0;this.N=d;a=this.qe;b=yz(a);a&&!b&&((b=g.Nb(a))&&b.match(Hga)?a="yt":(a=(a=g.Kb(g.Lb(5,a)))&&Iga.exec(a),a="ext-"+(!a||2>a.length?"":a[1].toLowerCase())),b=a);this.O=b;this.L=e;this.b=null};var Jga=function(a,b){1==a.o&&0<b&&(Jz(a),a.J=(0,g.G)()-1E3*b,Kz(a,"start"),a.o=2)};var Jz=function(a){a.D&&((0,window.clearTimeout)(a.D),a.D=null)};
var Lz=function(a){a.C&&((0,window.clearTimeout)(a.C),a.C=null)};var Kz=function(a,b){var c=a.L?a.L():"",c={docid:a.N,adid:a.g.sb,adfmt:a.O,waitTime:Math.floor((a.J||(new Date).getTime())-a.G),adsrc:a.g.source||"",flog:c,on3g:"mob"==g.kl()?"1":"0"},d="ns=yt&ps=blazer&playback=0&action=ad"+b;if(c)for(var e in c)null!=c[e]&&(d+="&"+e+"="+c[e]);e=d;c="/gen_204";(0,g.fn)()||(c="/gen_204");g.Ig(c+"?"+e)};var Mz=function(a,b){a.o=3;Jz(a);Lz(a);a.R();var c=(0,g.G)();Fz=c;g.Og("lastAdTime",""+c);b&&a.Hc("complete")};
var Kga=function(a){a.A||(a.G=(0,g.G)(),Kz(a,"uninit"));0==a.o&&(a.o=1,a.G=(0,g.G)(),Jz(a),a.D=(0,window.setTimeout)((0,g.x)(function(){Kz(this,"timeout");Mz(this,!1)},a),15E3))};var Nz=function(a,b){Hz.call(this,{start:a.quartile_0_url,firstQuartile:a.quartile_25_url,midpoint:a.quartile_50_url,thirdQuartile:a.quartile_75_url,end:a.quartile_100_url},b)};
var Oz=function(a,b,c){this.g=a;this.b=!1;a={start:g.Vb(b,{label:"part2viewed"}),firstQuartile:g.Vb(b,{label:"videoplaytime25"}),midpoint:g.Vb(b,{label:"videoplaytime50"}),thirdQuartile:g.Vb(b,{label:"videoplaytime75"}),end:g.Vb(b,{label:"videoplaytime100"})};Hz.call(this,a,c)};var Pz=function(a){this.FG=a;g.Di.call(this,Bga)};
var Qz=function(a,b){this.b=a;this.J=this.D=this.o=this.g=this.A=0;this.H=this.C=!1;this.G=null;this.F=0<=b.indexOf("hls_manifest");this.B=!(!b||this.F);this.L=new g.Oh;g.E(this,this.L);Lga(this)};var Mga=function(a,b){a.A<b&&(a.A=b)};
var Nga=function(a,b){if(!a.B)return!1;var c=(0,g.G)(),d=a.b.paused,e=a.b.ended;if(.2>b)return!1;0==a.g&&(a.g=c-b);e=b-(d&&!e?a.D:(c-a.g)/1E3);if(1<e&&b>a.A)return a.o=c,(0,window.setTimeout)((0,g.x)(function(){this.b.currentTime=this.J},a),0),a.H||(a.H=!0,g.Jg({action:"adsseekhead"})),!0;!d&&-.5>e&&(a.g=c-1E3*b);a.J=b;if(1500>c-a.o)return a.g=c-1E3*b,d&&a.C&&(a.C=!1,a.b.play()),!0;a.o=0;return!1};
var Lga=function(a){a.B&&uz(a.L,a.b,"play",(0,g.x)(function(){this.g=(0,g.G)()-1E3*this.b.currentTime;this.D=0},a),!1,"InStrAdDecorator")};var Rz=function(a){g.gy.call(this,a)};
var Sz=function(){g.Ny.call(this);this.Rb=this.b=null;this.aa=0;this.oj=!1;this.D=this.o="";this.M=this.g=this.X=this.L=null;this.ea=!1;this.C=new g.px;this.da=new g.By(g.Yd("html5_always_underrun_on_empty_buffer"));this.N=g.ol()?new g.jw:new g.iw;g.E(this,this.N);this.$a=g.Yd("html5_latch_for_seeking_on_event");this.hb=g.Yd("html5_playing_event_buffer_underrun");this.Sa=g.Yd("html5_ignore_first_timeupdate")};
var Tz=function(a,b){a.b=b;Uz(a)?a.tu(b):(a.Rb&&!a.Rb.qe&&Ez(a.video)&&a.Rb.Hc("impression"),a.Rb=null,a.mj(b))};
var Oga=function(a,b){var c=g.ew(a.Da,a.Hp,a.ja);c.ps="blazer";g.Yd("mweb_generate_cpn_on_page")||(c.cpn=a.R);var d=yz(b.getAttribute("src"));d&&"hls"==d&&(c.live_playback=1);var e=new g.fx(c);d&&(e.g=g.ex(b.getAttribute("src"),"video/mp4","small",d).getInfo());a.o&&(c.attrib="ad-trueview-insearch");c=new Rz(c);c.wd=b;d=new g.Jy(e,c,(0,g.x)(a.qT,a),function(){return b.duration},function(){return b.currentTime},(0,g.x)(a.rT,a),function(){return new g.Xn(b.clientWidth,b.clientHeight)},function(){return e.M});
d=new g.Px(d);g.E(a,d);vz(a.A,b,"play",(0,g.x)(d.zh,d),"BaseHtml5-play-once");a.Ca=new zz(b,e);g.E(a,a.Ca);a.N.ws(e);a.T=c;a.B=(0,g.x)(a.sT,a);g.fw(a.B);return d};
var Vz=function(a,b){(0,g.G)();if(g.Zm){a.g||(a.g=Oga(a,b),g.E(a,a.g));a.o&&!a.L&&(a.L=new Oz(a.o,a.D,a.video.sh),a.L.Ul(a.b));a.qa&&!a.X&&(a.X=new Nz(a.qa,a.video.sh),a.X.Ul(a.b));var c=uz(a.A,a.b,"timeupdate",(0,g.x)(function(){if(this.b&&0<this.b.currentTime&&0<this.b.duration){g.Qx(this.g);if(this.L){var a=this.L;a.b||(a.b=!0,g.$p(a.g))}this.b.removeEventListener("timeupdate",c,!1)}},a),!1,"MainVideoPlay");g.by(a.g)}};var Uz=function(a){return!(!a.Rb||3==a.Rb.o||!Ez(a.video))};
var Wz=function(a){a.oj=!0;g.Q(a,"overlay")};var Pga=function(a,b){(0,g.D)("loadstart loadeddata loadedmetadata play playing pause ended suspend progress seeking seeked timeupdate durationchange error waiting abort".split(" "),function(a){uz(this.A,b,a,(0,g.x)(this.tT,this),!1,"onVideoEvent")},a)};var Xz=function(){Sz.call(this);this.Z=!1;this.S=this.G=null};var Qga=function(a,b){var c="player_"+a.video.sb,d=g.fc(c);!d&&a.G&&a.G.id==c&&(d=a.G);d&&d.src!=b&&(a.Rm(d),d=null);return d};
var Yz=function(a,b){b.width=a?"2":"1";b.height=a?"1":"2"};var Rga=function(){var a={};g.Ka(Zz,function(b,c){if(Bz(c)){var d;d=""+c;d=g.Pd.get(d,void 0);a[c]=d}});return a};var Sga=function(a){g.Ka(a,function(a,c){Bz(c)||g.Od(c,a,Zz[c])})};var $z=function(){Sz.call(this);this.Z=!1};var aA=function(){g.Ny.call(this)};
g.jw.prototype.Tr=g.S(40,function(a){if(a&&a.target&&(g.Xk("pbs")||this.Hh("pbs"),a=a.target,!g.Xk("l2s")&&a&&2<g.Tn(a.buffered,a.currentTime))){if(this.b.videoId){var b=this.b.videoId;g.fl(void 0).docid=b}this.b.Wa&&(b=this.b.Wa,g.fl(void 0).cpn=b);0<this.b.ub&&(b=this.b.ub.toString(),g.fl(void 0).start=b);this.b.g&&(b=this.b.g.id.toString(),g.fl(void 0).fmt=b);b=Math.round(g.bo(this.o)*this.o.getDuration()).toString();g.fl(void 0).tds=b;this.Hh("l2s");g.Wk();a.removeEventListener("progress",this.B,
!1);a.removeEventListener("timeupdate",this.A,!1)}});g.jw.prototype.Hh=g.S(39,function(a){g.Tk(a)});g.jw.prototype.ws=g.S(38,function(a){this.b=a;this.B=uz(this.g,this.o,"progress",(0,g.x)(this.Tr,this),!1,"playback_csi");this.A=uz(this.g,this.o,"timeupdate",(0,g.x)(this.Tr,this),!1,"playback_csi");vz(this.g,this.o,"timeupdate",(0,g.x)(this.Hh,this,"aft"),"playback_csi_aft")});
g.jw.prototype.xs=g.S(37,function(a){this.o=a;uz(this.g,a,"loadedmetadata",(0,g.x)(this.Hh,this,"fvb"),!1,"playback_csi");uz(this.g,a,"loadstart",(0,g.x)(this.Hh,this,"gv"),!1,"playback_csi")});var Iga=/^.+\.([a-z0-9]{1,9})$/i,Aga=/[?&]itag=([0-9]*)/,zga=/\/manifest\/hls/,Hga=/^(.+\.)?youtube.com$/i,Ega=["22","83","82","18","36"],Dga=["36","17","13","18"];g.y(zz,g.Kc);
zz.prototype.H=function(){this.g=this.B.getCurrentTime();if(!this.B.paused&&(0<this.o&&this.g>this.o&&(this.D+=this.g-this.o),this.A&&0<this.C&&this.D>=this.C)){var a;this.b.w=(""+g.rq(this.g/this.A,0,1)).replace(",",".");this.b.l=this.A;a=g.Vb("/set_awesome",this.b);g.Dg(a);this.B.removeEventListener("timeupdate",this.G,!1)}this.o=this.g};zz.prototype.P=function(){zz.K.P.call(this);g.Pa(this)};g.y(Cz,g.My);Cz.prototype.Sh=!1;
Cz.prototype.Je=function(a,b){Cz.K.Je.call(this,a,b);this.width=g.zf?768:320;this.height=9*this.width/15;this.video&&(this.url=Az(this.Da,!1))};g.nt.embedflash=Cz;g.y(Dz,g.Di);Dz.prototype.b=function(){g.Cc(g.fc("content-container"),!0);this.Y()&&(g.rc(this.Y()),this.Y().style.height="");g.Df();this.unregister();g.Hc(window.document.body,"_mzb")};var Gga=g.Of(42E4),Fz=null;Gz.prototype.send=function(a,b){if(!this.b[a]){this.b[a]=!0;var c=this.g[a];c&&(g.ea(c)||(c=[c]),(0,g.D)(c,function(a){b&&(a=g.Vb(a,b));g.$p(a)}))}};g.y(Hz,g.Kc);g.h=Hz.prototype;g.h.Ul=function(a){this.A=a;a={pause:this.kD,playing:this.jf,ended:this.Ej,timeupdate:this.vv};for(var b in a)this.B[b]=uz(this.M,this.A,b,(0,g.x)(a[b],this),!1,"AdDecorator")};g.h.Vl=function(){for(var a in this.B)this.A.removeEventListener(a,this.B[a],!1)};g.h.jf=g.w;g.h.kD=g.w;g.h.Ej=g.w;
g.h.vv=function(){var a=this.A.currentTime/this.H;.75<a?this.Hc("thirdQuartile"):.5<a?this.Hc("midpoint"):.25<a&&this.Hc("firstQuartile")};g.h.Hc=function(a,b){this.S.send(a,b)};g.h.P=function(){Hz.K.P.call(this);g.Pa(this)};g.y(Iz,Hz);g.h=Iz.prototype;g.h.Ul=function(a){Iz.K.Ul.call(this,a);this.b=new Qz(this.A,this.qe);g.E(this,this.b);if(!this.qe)for(var b in this.B)"playing"!=b&&a.removeEventListener(b,this.B[b],!1)};
g.h.Vl=function(){Iz.K.Vl.call(this);if(this.b){var a=this.b;a.G&&(a.b.removeEventListener("ev",a.G,!1),a.G=null);this.b=null}Jz(this);Lz(this)};g.h.jf=function(){this.Hc("impression");this.Hc("creativeView");this.Hc("start");this.Hc("ptracking",{plid:this.W||g.Ef((0,g.G)(),1E13)})};g.h.kD=function(){Lz(this);1==this.o&&(Kz(this,"cancel"),Jz(this),this.o=0);this.b&&(this.b.D=this.A.currentTime)};g.h.Xs=function(){g.$p(this.g.Ru.click);g.Si(this.g.Wb)};
g.h.Ej=function(){var a;(a=!this.b)||(a=this.b,a=a.B&&a.o?a.C=!0:!a.F&&a.A<a.b.duration-1?!0:!1,a=!a);a&&(Kz(this,"finish"),Mz(this,!0))};g.h.vv=function(a){var b=this.A.currentTime;Jga(this,b);if(this.b){if(Nga(this.b,b)){Lz(this);return}Mga(this.b,b)}Iz.K.vv.call(this,a);this.F&&b>this.H-.3?this.Ej(a):b>this.H-4?(Lz(this),this.C=(0,window.setTimeout)((0,g.x)(function(){this.Ej(a)},this),1E3)):Lz(this)};g.y(Nz,Hz);Nz.prototype.jf=function(){this.Hc("start")};
Nz.prototype.Ej=function(){this.Hc("end");this.Vl()};g.y(Oz,Hz);Oz.prototype.jf=function(){this.Hc("start")};Oz.prototype.Ej=function(){this.Hc("end");this.Vl()};g.y(Pz,Dz);g.y(Qz,g.Kc);Qz.prototype.P=function(){Qz.K.P.call(this);g.Pa(this)};var cA;cA=g.vf(function(){return!!window.document.createElement("video").textTracks});g.y(Rz,g.gy);g.y(Sz,g.Ny);g.h=Sz.prototype;g.h.Ju=g.Mm;g.h.Je=function(a,b){Sz.K.Je.call(this,a,b);g.Yd("mweb_generate_cpn_on_page")&&(this.R=b&&b.md&&b.md.cpn||"");if(b&&b.md.ttsurl&&this.video&&cA()&&!this.M){var c=g.Pb(b.md.ttsurl);this.M=new g.zy(c,a.sb);this.M.fo((0,g.x)(this.UB,this),void 0,"vtt")}};g.h.wi=function(){return!!this.Da&&!(this.Da.md&&this.Da.md.hlsvp)&&Az(this.Da,!0)!=Az(this.Da,!1)};g.h.UB=function(){this.b&&this.M&&!this.ea&&(this.ea=!0,g.ao(this.b,this.M.Yq()))};g.h.jf=g.w;
g.h.ut=g.w;g.h.lr=function(a){return(0,g.I)(a.oj?'<div class="_myo" style="background:#000"><div class="_mzo"><canvas data-spinner-color="255,255,255" class="_mf _map"></div></div>':g.Xm?"":g.Dt())};g.h.Ug=function(){var a=g.Gl.getTag(void 0,void 0);g.jc(a,{poster:g.Po(),id:"player_"+this.video.sb});g.tm&&a.setAttribute("x-webkit-airplay","allow");Pga(this,a);uz(this.A,a,"error",(0,g.x)(this.VJ,this),!1,"playerBase");uz(this.A,a,"contextmenu",function(a){a.preventDefault()});this.N.xs(a);return a};
g.h.oq=function(){this.Rb.Vl();this.mj(this.b);this.b.load();Vz(this,this.b);this.b.play()};g.h.wg=function(){this.sk()};g.h.VJ=function(a){var b;a:{if(a&&a.target&&3<g.Hf&&(this.aa++,10>=this.aa)){window.setTimeout((0,g.x)(a.target.load,a.target),500);b=!0;break a}b=!1}if(b)return!1;a.target.error&&"hls"==yz(a.target.src)&&(this.sk(),window.alert(Fga()));return!1};
g.h.sl=function(a){!Uz(this)&&g.Mo()!=a&&this.wi()&&this.b&&(g.jc(this.b,{src:this.getVideoUrl(a)}),(0,window.setTimeout)((0,g.x)(function(){this.b.load();(g.X(this.C,1)||g.X(this.C,8))&&this.b.play()},this),0))};g.h.vl=function(){var a=this.Y("playbug");a&&(g.Fc(a,"_msc"),g.ti("BaseHTML5.showHQStatus",function(){a&&g.Hc(a,"_msc")},1E3,this))};g.h.play=function(){this.b&&(this.N.Jp(),this.UB(),this.Rb?Kga(this.Rb):Vz(this,this.b),this.gB())};g.h.uv=function(a){this.b&&(this.b.currentTime=a)};
g.h.mj=function(a){this.ja=g.Ef((0,g.G)(),1E13);g.Yd("mweb_generate_cpn_on_page")||(this.R=g.Rv());g.jc(a,{src:this.getVideoUrl(),title:this.video.title})};g.h.tu=function(a){g.jc(a,{src:this.Rb.qe});this.Rb.Ul(a)};g.h.Tl=function(a,b,c,d){Sz.K.Tl.call(this,a,b,c,d);a&&Ez(this.video)&&(this.Rb=new Iz(a,this.ja,(0,g.x)(this.oq,this),this.video.sb,this.Ba?(0,g.x)(this.Ba,this):null));b&&(this.o=b);c&&(this.D=c);d&&(this.qa=d)};g.h.sk=function(){this.oj=!1;g.Q(this,"overlay")};
g.h.Rm=function(a){g.sc(a);g.up(a)};g.h.Aa=function(){this.B&&(g.hw(this.B),this.B=null);Sz.K.Aa.call(this);this.Rm(this.b);this.b=null;this.oj=!1;this.C=new g.px;this.Ka&&this.Ka()};g.h.getVideoUrl=function(a){a=this.Da.md&&this.Da.md.hlsvp||null||Az(this.Da,a)||"";var b={};this.R&&(b.cpn=this.R);return g.Vb(a,b)};g.h.stop=function(){this.b&&this.b.pause()};g.h.getCurrentTime=function(){return!this.ha()&&this.b?Math.round(this.b.currentTime):Sz.K.getCurrentTime.call(this)};
g.h.tT=function(a){var b=a.target;if(b==this.b&&b.currentSrc&&this.display&&(this.$a&&"seeking"==a.type&&g.Cy(this.da,this.getCurrentTime()),b=new g.Gy(b),a=g.qx(this.C,new g.Fy(b,a.type),this.da,this.hb,this.Sa),!g.vx(this.C,a))){b=new g.Ky(a,this.C);if(g.X(a,2)){this.g&&g.cy(this.g);if(this.b&&g.If)try{this.b.currentTime=.1}catch(c){}this.ut()}else g.X(a,8)?(this.g&&this.g.hc(b),this.jf()):g.X(a,4)?(this.g&&this.g.hc(b),this.ut()):this.g&&this.g.hc(b);this.C=a}};
g.h.sT=function(){this.T&&(this.T.U0=(0,g.G)())};g.h.qT=function(){return{mos:0,volume:100}};g.h.rT=function(){var a=new g.Hy;!this.ha()&&this.b&&(a.b=g.Ap(this.b.buffered,this.getCurrentTime()));return a};g.y(Xz,Sz);g.h=Xz.prototype;g.h.Sh=!g.Um;
g.h.Ug=function(a){var b;b=a?this.Rb.qe:this.getVideoUrl();var c=Qga(this,b);if(c)return c;this.oj&&Wz(this);c=Xz.K.Ug.call(this,a);g.Fc(c,"_mtc");Yz(g.Uh(),c);(g.Xm||g.np()&&g.If)&&g.jc(c,{preload:"none"});g.If&&3!=g.Hf&&(a=g.ma(Sga,Rga()),g.Nh(c,"pause",a,!1,"FSHTML5"),g.Nh(c,"error",a,!1,"FSHTML5"));c.onwebkitendfullscreen&&4<=g.Hf&&!g.n(window.document.webkitIsFullScreen)?g.Cp(c,"webkitendfullscreen",(0,g.x)(this.Ip,this)):g.Cp(c,"play",(0,g.x)(this.Ip,this));g.If&&g.Cp(c,"play",(0,g.x)(function(){this.Z||
this.play()},this));g.n(window.document.webkitIsFullScreen)&&g.Nh(c,"webkitfullscreenchange",(0,g.x)(function(){window.document.webkitIsFullScreen||c.pause()},this),!1,"FSHTML5-ExitPause");return this.G=c};g.h.za=function(a){Xz.K.za.call(this,a);a||!(g.Xm||g.If&&3>=g.Hf)&&g.np()&&g.If||(a=this.Ug(Uz(this)),Tz(this,a),g.fc("player").appendChild(a),g.Xm||a.load())};
g.h.mj=function(a){Xz.K.mj.call(this,a);g.ih(a,"ended",function(){try{window.document.webkitExitFullscreen&&!g.Vm?window.document.webkitExitFullscreen():window.document.exitFullscreen?window.document.exitFullscreen():a.webkitExitFullScreen&&a.webkitExitFullScreen()}catch(b){}})};g.h.play=function(){if(g.$m&&this.oj)this.sk(),this.b.pause();else{if(g.np()&&g.If){var a=this.Ug(Uz(this));Tz(this,a)}Xz.K.play.call(this)}};
g.h.gB=function(){this.Z=!0;var a;(a=0<this.b.currentTime||!this.Rb)||(a=this.Rb,a=!(g.Mm&&a.qe&&3!=a.o));a||g.np()?this.hB():(a=new Pz(this.Rb.g),g.Cc(g.fc("content-container"),!1),g.Bf(),a.register(g.fc("lightbox")),g.Fc(window.document.body,"_mzb"),(0,window.setTimeout)((0,g.x)(this.hB,this),2E3),(0,window.setTimeout)((0,g.x)(a.b,a),5E3))};
g.h.hB=function(){var a=this.b;if(g.Um){var b=window.document.createEvent("HTMLEvents");b.initEvent("playing",!0,!0);a.dispatchEvent(b)}g.If&&a.ended&&a.load();g.$m?(Wz(this),g.Cp(a,"playing",(0,g.x)(this.wg,this)),g.If&&!this.S&&(this.S=g.n(window.document.webkitIsFullScreen)?g.Nh(a,"webkitfullscreenchange",(0,g.x)(function(){window.document.webkitIsFullScreen||this.sk()},this),!1,"FSHTML5-SC"):g.Nh(a,"webkitendfullscreen",(0,g.x)(this.sk,this),!1,"FSHTML5-EFS"))):(g.Cp(a,"playing",(0,g.x)(this.wg,
this)),(g.Ym||4<=g.Vh)&&(a.webkitEnterFullScreen||a.webkitRequestFullscreen||a.requestFullscreen)&&(a.webkitRequestFullscreen&&!g.Vm?a.webkitRequestFullscreen():a.requestFullscreen?a.requestFullscreen():a.webkitEnterFullScreen(),g.n(window.document.webkitIsFullScreen)||g.Cp(a,"webkitendfullscreen",(0,g.x)(a.pause,a)),4.1>g.Vh&&!g.Sm&&g.Cp(a,"durationchange",function(){a.pause();(0,window.setTimeout)((0,g.x)(a.play,a),0)})));g.np()&&g.If&&(a.load(),g.fc("player").appendChild(a));g.Xm&&a.load();a.play()};
g.h.wg=function(){Xz.K.wg.call(this);this.b.removeEventListener(g.n(window.document.webkitIsFullScreen)?"webkitfullscreenchange":"webkitendfullscreen",this.S,!1)};g.h.Rm=function(a){a==this.G&&(this.G=null);Xz.K.Rm.call(this,a)};g.h.Aa=function(){Xz.K.Aa.call(this)};g.h.Zb=function(a){Xz.K.Zb.call(this,a);if(g.If){var b=g.hc("video",void 0,void 0);a=g.ma(Yz,a);(0,g.D)(b,a)}};var Zz={VISITOR_INFO1_LIVE:20736E3,PREF:31536E4};g.nt.html5fs=Xz;g.y($z,Sz);g.h=$z.prototype;g.h.Sh=!1;g.h.Dj=function(a){a=a||{};var b=g.I,c,d=a;c="";if(null==d.Rb?0:d.Rb.qe){var d='<div class="_mbp" '+g.L(g.P("instreamInlineOverlay"))+'><div class="_mcp"><span class="_mdp">Advertisement</span></div><div class="_mep"><a href="#" '+g.L((0,g.ui)(d.Xs))+'class="_mfp"><div class="_mgp">',e;e=(0,g.I)("Visit advertiser's site");c=c+(d+g.H(e)+"</div></a></div></div>")}c=(0,g.I)(c);return b(c+g.Ct(a))};
g.h.Ug=function(a){a=$z.K.Ug.call(this,a);g.Gc(a,["_muc","_mvc","_mwc"]);if(4<=g.Vh||10<=g.Zh||g.tn)g.n(window.document.webkitIsFullScreen)?uz(this.A,a,"webkitfullscreenchange",(0,g.x)(function(){window.document.webkitIsFullScreen||this.Oj()},this,!0),!1,"InlineHTML5-ASize"):uz(this.A,a,"webkitendfullscreen",(0,g.x)(this.Oj,this,!0),!1,"InlineHTML5-ASize");return a};g.h.mj=function(a){$z.K.mj.call(this,a);g.jc(a,{controls:"1"})};
g.h.tu=function(a){$z.K.tu.call(this,a);var b=uz(this.A,a,"click",function(){a.paused?a.play():a.pause()},!1,"InlineHTML5");this.S=function(){a.removeEventListener("click",b,!1);this.S=g.w}};g.h.oq=function(){this.S();var a=this.Y("instreamInlineOverlay");a&&g.Hc(a,"_mxc");$z.K.oq.call(this)};g.h.play=function(){if(g.X(this.C,64)){var a=this.Ug(Uz(this));Tz(this,a);4<=g.Vh&&this.Oj(!1);var b=this.Y("instreamInlineOverlay");b&&g.ti("InlineAdShow",function(){g.Fc(b,"_mxc")},500,this);$z.K.play.call(this)}};
g.h.gB=function(){var a=this.b;if(!this.G&&a){this.G=!0;var b=this.Y("watchImageThumbnail");(0,window.setTimeout)(g.ma(g.qc,b,a),0);a=this.b;Wz(this);vz(this.A,a,"timeupdate",(0,g.x)(this.wg,this),"Inline-OnPlayStart");g.km?(0,window.setTimeout)((0,g.x)(a.play,a),0):a.play();(a=g.ic("_myc"))&&g.Fc(a,"_msb");a=this.b;g.Hc(a,"_mwc");g.Fc(a,"_mzc")}};g.h.Xs=function(){this.Rb.Xs()};
g.h.wg=function(){var a=this.b;a&&(0<a.currentTime?(this.Z=!0,this.Oj(!0),$z.K.wg.call(this)):g.Cp(a,"timeupdate",(0,g.x)(this.wg,this)))};
g.h.Oj=function(a){if(this.display&&this.Y()){var b=this.Y(g.zf?"watchPlayerArea":"watchImageThumbnail"),c=this.b;if(b&&c&&this.Z){var d=c.videoWidth/c.videoHeight,e,f;g.zf?(f=b.clientWidth,e=Math.min(f/(16/9),f/d,487)):(f=Math.min(window.innerWidth,768),e=Math.min(f/d,f/(16/9),g.fe/2));d*=e;c.style.width=d+"px";c.style.height=e+"px";f=(f-d)/2;c.style.marginLeft=f+"px";c.style.marginRight=f+"px";g.zf&&(e=(b.clientHeight-e)/2,c.style.marginTop=e+"px",c.style.marginBottom=e+"px");a&&(b.style.visibility=
"hidden",(0,window.setTimeout)(function(){b.style.visibility=""},0))}}};g.h.Zb=function(a){$z.K.Zb.call(this,a);(4<=g.Vh||10<=g.Zh||g.tn||g.Um)&&this.Oj()};g.h.stop=function(){$z.K.stop.call(this);var a=g.ic(g.zf?"_mad":"_mbd");a&&g.Fc(a,"_msb")};g.h.Aa=function(){this.G=!1;$z.K.Aa.call(this)};g.nt.html5=$z;g.y(aA,g.Ny);aA.prototype.play=function(){if(this.video){var a=Az(this.Da,"rtsp"==this.ma||"rtspconn"==this.ma)||"";this.Ip();g.uf(a)}};g.nt["vnd.youtube"]=aA;g.nt["vnd.youtube.http"]=aA;g.nt["vnd.rim"]=aA;g.nt.rtsp=aA;g.nt.rtspconn=aA;g.nt.crawler=aA;g.nt.http=aA;})(_yt_m);
